# Generated by Django 5.2.14 on 2026-05-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shortcutsection_shortcut_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shortcut_icons/'),
        ),
    ]
