# Generated by Django 5.2.14 on 2026-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shortcut_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcut',
            options={'ordering': ['-is_favorite', 'order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='shortcutsection',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='shortcut',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortcutsection',
            name='color',
            field=models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('purple', 'Lila'), ('orange', 'Orange'), ('red', 'Rot')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='shortcutsection',
            name='is_collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortcutsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
