# Generated by Django 6.0.4 on 2026-05-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shortcut_options_alter_shortcutsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcut',
            options={'ordering': ['order', 'created_at']},
        ),
    ]
