# Generated by Django 5.2.14 on 2026-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_avatarcharacter_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(choices=[('blue', 'Blau'), ('purple', 'Lila'), ('green', 'Grün'), ('orange', 'Orange'), ('red', 'Rot'), ('gray', 'Grau')], default='blue', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notiz',
                'verbose_name_plural': 'Notizen',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
    ]
