# Generated by Codex on 2026-05-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_weatherlocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_view_notes", models.BooleanField(default=True)),
                ("can_create_notes", models.BooleanField(default=True)),
                ("can_edit_notes", models.BooleanField(default=True)),
                ("can_delete_notes", models.BooleanField(default=True)),
                ("can_pin_notes", models.BooleanField(default=True)),
                ("can_archive_notes", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notiz-Recht",
                "verbose_name_plural": "Notiz-Rechte",
            },
        ),
    ]
