# Generated by Django 5.2.14 on 2026-05-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanBenchmarkHighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('reaction', 'Reaktion'), ('aim', 'Aim Trainer'), ('typing', 'Typing Test'), ('visual', 'Visual Memory')], max_length=20)),
                ('score', models.FloatField()),
                ('display_score', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_benchmark_highscores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Human Benchmark Highscore',
                'verbose_name_plural': 'Human Benchmark Highscores',
                'indexes': [models.Index(fields=['game', 'score'], name='app_humanbe_game_7a53cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='unique_human_benchmark_highscore_per_user_game')],
            },
        ),
        migrations.CreateModel(
            name='HumanBenchmarkScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('reaction', 'Reaktion'), ('aim', 'Aim Trainer'), ('typing', 'Typing Test'), ('visual', 'Visual Memory')], max_length=20)),
                ('score', models.FloatField()),
                ('display_score', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_benchmark_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Human Benchmark Ergebnis',
                'verbose_name_plural': 'Human Benchmark Ergebnisse',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game', '-created_at'], name='app_humanbe_user_id_9b77e5_idx'), models.Index(fields=['game', 'score'], name='app_humanbe_game_ee7936_idx')],
            },
        ),
    ]
