# Generated by Django 5.2.14 on 2026-05-27 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_humanbenchmarkhighscore_humanbenchmarkscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('widget_type', models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken')], default='weather', max_length=30)),
                ('color', models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('purple', 'Lila'), ('orange', 'Orange'), ('red', 'Rot')], default='blue', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_widgets', to=settings.AUTH_USER_MODEL)),
                ('weather_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_widgets', to='app.weatherlocation')),
            ],
            options={
                'verbose_name': 'Home-Widget',
                'verbose_name_plural': 'Home-Widgets',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['user', 'order', 'created_at'], name='app_homewid_user_id_0ecaaa_idx')],
            },
        ),
    ]
