# Generated by Django 5.2.14 on 2026-05-27 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_homewidget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLayoutPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_area_order', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_layout_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home-Layout-Einstellung',
                'verbose_name_plural': 'Home-Layout-Einstellungen',
            },
        ),
    ]
