# Generated by Django 5.2.14 on 2026-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_homelayoutpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='homewidget',
            name='clock_design',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('glass', 'Glass'), ('neon', 'Neon'), ('flip', 'Flip'), ('terminal', 'Terminal')], default='minimal', max_length=20),
        ),
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('clock', 'Uhr')], default='weather', max_length=30),
        ),
    ]
