# Generated by Django 5.2.14 on 2026-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_homewidget_clock_design_alter_homewidget_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homewidget',
            name='clock_style',
            field=models.CharField(choices=[('classic', 'Klassisch'), ('compact', 'Kompakt'), ('split', 'Datum links'), ('analog', 'Analog'), ('hybrid', 'Analog + Digital')], default='classic', max_length=20),
        ),
    ]
