# Generated by Django 5.2.14 on 2026-05-27 13:56

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_homewidget_clock_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homewidget',
            name='clock_design',
        ),
        migrations.RemoveField(
            model_name='homewidget',
            name='clock_style',
        ),
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken')], default='weather', max_length=30),
        ),
        migrations.CreateModel(
            name='ClockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField(default=80)),
                ('ringtone', models.CharField(choices=[('bell', 'Bell'), ('chime', 'Chime'), ('digital', 'Digital'), ('soft', 'Soft'), ('alarm', 'Alarm'), ('custom', 'Eigener Ton')], default='bell', max_length=20)),
                ('custom_sound', models.FileField(blank=True, null=True, upload_to=app.models.clock_sound_upload_path, validators=[app.models.validate_clock_sound_size])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clock_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uhr-Einstellung',
                'verbose_name_plural': 'Uhr-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='ClockTimerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('hours', models.PositiveSmallIntegerField(default=0)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('seconds', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_timer_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timer-Vorlage',
                'verbose_name_plural': 'Timer-Vorlagen',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['user', 'order', 'created_at'], name='app_clockti_user_id_31f32d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClockWorldCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('timezone', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_world_cities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weltuhr-Ort',
                'verbose_name_plural': 'Weltuhr-Orte',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['user', 'order', 'created_at'], name='app_clockwo_user_id_90eb33_idx')],
            },
        ),
    ]
