# Generated by Django 5.2.14 on 2026-05-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homewidget',
            name='weather_design',
            field=models.CharField(choices=[('clean', 'Clean'), ('glass', 'Glass'), ('aurora', 'Aurora'), ('sunset', 'Sunset'), ('night', 'Night')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='homewidget',
            name='weather_style',
            field=models.CharField(choices=[('classic', 'Klassisch'), ('hero', 'Groß'), ('compact', 'Kompakt'), ('split', 'Geteilt')], default='classic', max_length=20),
        ),
    ]
