# Generated by Django 5.2.14 on 2026-05-29 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_homewidget_weather_design_homewidget_weather_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Befreundet')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freundschaft',
                'verbose_name_plural': 'Freundschaften',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['from_user', 'status'], name='app_friends_from_us_db5ea6_idx'), models.Index(fields=['to_user', 'status'], name='app_friends_to_user_435fef_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_friendship_request_direction'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='friendship_prevent_self_request')],
            },
        ),
    ]
