# Generated by Django 5.2.14 on 2026-05-29 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingGameLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zeichen-Lobby', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('rounds_count', models.PositiveSmallIntegerField(default=3)),
                ('draw_time_seconds', models.PositiveSmallIntegerField(default=80)),
                ('max_players', models.PositiveSmallIntegerField(default=8)),
                ('custom_words', models.TextField(blank=True)),
                ('use_only_custom_words', models.BooleanField(default=False)),
                ('current_round_number', models.PositiveSmallIntegerField(default=1)),
                ('current_turn_index', models.PositiveIntegerField(default=0)),
                ('current_word', models.CharField(blank=True, max_length=80)),
                ('current_word_choices', models.JSONField(blank=True, default=list)),
                ('current_drawing', models.JSONField(blank=True, default=list)),
                ('round_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_drawing_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zeichenspiel-Lobby',
                'verbose_name_plural': 'Zeichenspiel-Lobbys',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingGameInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_drawing_invites', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_drawing_invites', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.drawinggamelobby')),
            ],
            options={
                'verbose_name': 'Zeichenspiel-Einladung',
                'verbose_name_plural': 'Zeichenspiel-Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingGameGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('turn_index', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(max_length=160)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_game_guesses', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='app.drawinggamelobby')),
            ],
            options={
                'verbose_name': 'Zeichenspiel-Rateversuch',
                'verbose_name_plural': 'Zeichenspiel-Rateversuche',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('avatar_base', models.CharField(choices=[('round', 'Rund'), ('square', 'Eckig'), ('robot', 'Roboter'), ('cat', 'Katze'), ('ghost', 'Geist'), ('ninja', 'Ninja')], default='round', max_length=20)),
                ('avatar_color', models.CharField(default='#4f8cff', max_length=20)),
                ('accent_color', models.CharField(default='#ffffff', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('has_guessed_current_word', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.drawinggamelobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_game_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zeichenspiel-Spieler',
                'verbose_name_plural': 'Zeichenspiel-Spieler',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='drawinggamelobby',
            index=models.Index(fields=['code'], name='app_drawing_code_600fee_idx'),
        ),
        migrations.AddIndex(
            model_name='drawinggamelobby',
            index=models.Index(fields=['owner', 'status'], name='app_drawing_owner_i_a1be04_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawinggameinvite',
            constraint=models.UniqueConstraint(fields=('lobby', 'to_user'), name='unique_drawing_invite_per_lobby_user'),
        ),
        migrations.AddConstraint(
            model_name='drawinggameinvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='drawing_invite_prevent_self'),
        ),
        migrations.AddIndex(
            model_name='drawinggameguess',
            index=models.Index(fields=['lobby', 'round_number', 'turn_index', 'created_at'], name='app_drawing_lobby_i_26d0df_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawinggameplayer',
            constraint=models.UniqueConstraint(fields=('lobby', 'user'), name='unique_drawing_player_per_lobby'),
        ),
    ]
