# Generated by Django 5.2.14 on 2026-05-29 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_chatroom_chatroommember_chatroom_members_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', '👍'), ('❤️', '❤️'), ('😂', '😂'), ('😮', '😮'), ('😢', '😢'), ('🙏', '🙏')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatreaktion',
                'verbose_name_plural': 'Chatreaktionen',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'emoji'], name='app_chatmes_message_b6319f_idx'), models.Index(fields=['user', 'updated_at'], name='app_chatmes_user_id_1e61b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_chat_message_reaction')],
            },
        ),
    ]
