# Generated by Django 5.2.14 on 2026-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_chatmessagereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('clock', 'Uhr'), ('chat', 'Chats'), ('friends', 'Freunde'), ('skribble', 'Skribble')], default='weather', max_length=30),
        ),
    ]
