# Generated by Django 5.2.14 on 2026-05-29 12:29

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_userpresence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy_show_chat_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_show_friends',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_show_highscores',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_show_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('busy', 'Beschäftigt'), ('away', 'Abwesend'), ('dnd', 'Nicht stören'), ('invisible', 'Unsichtbar')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, max_length=1200),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.chat_attachment_upload_path, validators=[app.models.validate_chat_attachment_size])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.chatmessage')),
            ],
            options={
                'verbose_name': 'Chat-Anhang',
                'verbose_name_plural': 'Chat-Anhänge',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('system', 'System'), ('chat', 'Chat'), ('friend', 'Freunde'), ('skribble', 'Skribble'), ('feedback', 'Feedback')], default='system', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='fa-solid fa-bell', max_length=80)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox-Eintrag',
                'verbose_name_plural': 'Inbox-Einträge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='app_inboxit_user_id_82427d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_key', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool-Favorit',
                'verbose_name_plural': 'Tool-Favoriten',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'tool_key'], name='app_toolfav_user_id_7c1608_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tool_key'), name='unique_tool_favorite_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ToolFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_key', models.CharField(blank=True, max_length=60)),
                ('feedback_type', models.CharField(choices=[('feedback', 'Feedback'), ('bug', 'Bug'), ('idea', 'Feature-Idee')], default='feedback', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('planned', 'Geplant'), ('done', 'Erledigt')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool-Feedback',
                'verbose_name_plural': 'Tool-Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_key', 'status', '-created_at'], name='app_toolfee_tool_ke_979b2d_idx')],
            },
        ),
    ]
