# Generated by Django 5.2.14 on 2026-05-29 12:46

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_userprofile_privacy_show_chat_button_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_group_avatars/'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='browser_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dnd_silence_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_friend_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_skribble',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sound_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SkribbleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('correct_guesses', models.PositiveIntegerField(default=0)),
                ('drawings_made', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skribble_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skribble-Statistik',
                'verbose_name_plural': 'Skribble-Statistiken',
            },
        ),
        migrations.CreateModel(
            name='ChatMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='app.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gelesene Chatnachricht',
                'verbose_name_plural': 'Gelesene Chatnachrichten',
                'ordering': ['read_at'],
                'indexes': [models.Index(fields=['message', 'user'], name='app_chatmes_message_b48f01_idx'), models.Index(fields=['user', 'read_at'], name='app_chatmes_user_id_b7cb87_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_chat_message_read_user')],
            },
        ),
        migrations.CreateModel(
            name='ProfileGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.profile_gallery_upload_path)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil-Galeriebild',
                'verbose_name_plural': 'Profil-Galeriebilder',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_profile_user_id_9f4c01_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockierter Nutzer',
                'verbose_name_plural': 'Blockierte Nutzer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='app_userblo_blocker_22a2a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='prevent_self_block')],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Belästigung'), ('content', 'Unpassende Inhalte'), ('other', 'Sonstiges')], default='other', max_length=30)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzermeldung',
                'verbose_name_plural': 'Nutzermeldungen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reported', 'is_resolved', '-created_at'], name='app_userrep_reporte_5435c2_idx')],
            },
        ),
    ]
