# Generated by Django 6.0.5 on 2026-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_chatroom_avatar_chatroom_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawinggameguess',
            name='drawer_points_awarded',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drawinggameguess',
            name='points_awarded',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drawinggamelobby',
            name='round_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='drawinggamelobby',
            name='summary_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drawinggamelobby',
            name='status',
            field=models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('round_summary', 'Rundenuebersicht'), ('finished', 'Beendet')], default='waiting', max_length=20),
        ),
    ]
