# Generated by Django 6.0.5 on 2026-05-30 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_drawinggameguess_drawer_points_awarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('clock', 'Uhr'), ('chat', 'Chats'), ('friends', 'Freunde'), ('skribble', 'Skribble'), ('tictactoe', 'Tic Tac Toe')], default='weather', max_length=30),
        ),
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tic Tac Toe', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('board', models.JSONField(blank=True, default=list)),
                ('current_symbol', models.CharField(choices=[('X', 'X'), ('O', 'O')], default='X', max_length=1)),
                ('winner_symbol', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O')], max_length=1)),
                ('winning_line', models.JSONField(blank=True, default=list)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tictactoe_games', to=settings.AUTH_USER_MODEL)),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tictactoe_games_as_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tictactoe_games_as_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tic Tac Toe Spiel',
                'verbose_name_plural': 'Tic Tac Toe Spiele',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['code'], name='app_tictact_code_ab87fe_idx'), models.Index(fields=['owner', 'status'], name='app_tictact_owner_i_92f50b_idx'), models.Index(fields=['player_x', 'status'], name='app_tictact_player__881c4d_idx'), models.Index(fields=['player_o', 'status'], name='app_tictact_player__4bfc30_idx')],
            },
        ),
    ]
