# Generated by Django 6.0.5 on 2026-05-30 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_homewidget_widget_type_tictactoegame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tictactoe_invites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.tictactoegame')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tictactoe_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tic Tac Toe Einladung',
                'verbose_name_plural': 'Tic Tac Toe Einladungen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'status'], name='app_tictact_to_user_d2dabb_idx'), models.Index(fields=['game', 'status'], name='app_tictact_game_id_bdd81a_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'to_user'), name='unique_tictactoe_invite_per_game_user'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='tictactoe_invite_prevent_self')],
            },
        ),
    ]
