# Generated by Django 6.0.5 on 2026-05-30 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_tictactoeinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleshipGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Schiffe versenken', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('setup', 'Flottenaufbau'), ('playing', 'Läuft'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('fleet_a', models.JSONField(blank=True, default=list)),
                ('fleet_b', models.JSONField(blank=True, default=list)),
                ('shots_a', models.JSONField(blank=True, default=list)),
                ('shots_b', models.JSONField(blank=True, default=list)),
                ('ready_a', models.BooleanField(default=False)),
                ('ready_b', models.BooleanField(default=False)),
                ('current_turn', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('winner_side', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_battleship_games', to=settings.AUTH_USER_MODEL)),
                ('player_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_games_as_a', to=settings.AUTH_USER_MODEL)),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_games_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schiffe versenken Spiel',
                'verbose_name_plural': 'Schiffe versenken Spiele',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleshipInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_battleship_invites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.battleshipgame')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_battleship_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schiffe versenken Einladung',
                'verbose_name_plural': 'Schiffe versenken Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='battleshipgame',
            index=models.Index(fields=['code'], name='app_battles_code_258a73_idx'),
        ),
        migrations.AddIndex(
            model_name='battleshipgame',
            index=models.Index(fields=['owner', 'status'], name='app_battles_owner_i_5b941b_idx'),
        ),
        migrations.AddIndex(
            model_name='battleshipgame',
            index=models.Index(fields=['player_a', 'status'], name='app_battles_player__aebf61_idx'),
        ),
        migrations.AddIndex(
            model_name='battleshipgame',
            index=models.Index(fields=['player_b', 'status'], name='app_battles_player__4dfd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='battleshipinvite',
            index=models.Index(fields=['to_user', 'status'], name='app_battles_to_user_50e6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='battleshipinvite',
            index=models.Index(fields=['game', 'status'], name='app_battles_game_id_685368_idx'),
        ),
        migrations.AddConstraint(
            model_name='battleshipinvite',
            constraint=models.UniqueConstraint(fields=('game', 'to_user'), name='unique_battleship_invite_per_game_user'),
        ),
        migrations.AddConstraint(
            model_name='battleshipinvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='battleship_invite_prevent_self'),
        ),
    ]
