# Generated by Django 6.0.5 on 2026-05-31 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_battleshipgame_battleshipinvite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('clock', 'Uhr'), ('chat', 'Chats'), ('friends', 'Freunde'), ('skribble', 'Skribble'), ('tictactoe', 'Tic Tac Toe'), ('stadtlandfluss', 'Stadt Land Fluss')], default='weather', max_length=30),
        ),
        migrations.CreateModel(
            name='StadtLandFlussLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stadt Land Fluss', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'LÃ¤uft'), ('round_summary', 'Rundenauswertung'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('rounds_count', models.PositiveSmallIntegerField(default=5)),
                ('round_time_seconds', models.PositiveSmallIntegerField(default=90)),
                ('max_players', models.PositiveSmallIntegerField(default=8)),
                ('current_round_number', models.PositiveSmallIntegerField(default=0)),
                ('current_letter', models.CharField(blank=True, max_length=1)),
                ('used_letters', models.JSONField(blank=True, default=list)),
                ('round_started_at', models.DateTimeField(blank=True, null=True)),
                ('round_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stadtlandfluss_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stadt Land Fluss Lobby',
                'verbose_name_plural': 'Stadt Land Fluss Lobbys',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StadtLandFlussInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_stadtlandfluss_invites', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_stadtlandfluss_invites', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.stadtlandflusslobby')),
            ],
            options={
                'verbose_name': 'Stadt Land Fluss Einladung',
                'verbose_name_plural': 'Stadt Land Fluss Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StadtLandFlussPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('score', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.stadtlandflusslobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadtlandfluss_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stadt Land Fluss Spieler',
                'verbose_name_plural': 'Stadt Land Fluss Spieler',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='StadtLandFlussRoundAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('letter', models.CharField(max_length=1)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('points', models.JSONField(blank=True, default=dict)),
                ('total_points', models.PositiveSmallIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.stadtlandflusslobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.stadtlandflussplayer')),
            ],
            options={
                'verbose_name': 'Stadt Land Fluss Antwort',
                'verbose_name_plural': 'Stadt Land Fluss Antworten',
                'ordering': ['round_number', 'player__joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stadtlandflusslobby',
            index=models.Index(fields=['code'], name='app_stadtla_code_6886d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stadtlandflusslobby',
            index=models.Index(fields=['owner', 'status'], name='app_stadtla_owner_i_2ebe9e_idx'),
        ),
        migrations.AddIndex(
            model_name='stadtlandflussinvite',
            index=models.Index(fields=['to_user', 'status'], name='app_stadtla_to_user_c1deb8_idx'),
        ),
        migrations.AddIndex(
            model_name='stadtlandflussinvite',
            index=models.Index(fields=['lobby', 'status'], name='app_stadtla_lobby_i_496ad8_idx'),
        ),
        migrations.AddConstraint(
            model_name='stadtlandflussinvite',
            constraint=models.UniqueConstraint(fields=('lobby', 'to_user'), name='unique_stadtlandfluss_invite_per_lobby_user'),
        ),
        migrations.AddConstraint(
            model_name='stadtlandflussinvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='stadtlandfluss_invite_prevent_self'),
        ),
        migrations.AddConstraint(
            model_name='stadtlandflussplayer',
            constraint=models.UniqueConstraint(fields=('lobby', 'user'), name='unique_stadtlandfluss_player_per_lobby'),
        ),
        migrations.AddIndex(
            model_name='stadtlandflussroundanswer',
            index=models.Index(fields=['lobby', 'round_number'], name='app_stadtla_lobby_i_979185_idx'),
        ),
        migrations.AddConstraint(
            model_name='stadtlandflussroundanswer',
            constraint=models.UniqueConstraint(fields=('lobby', 'player', 'round_number'), name='unique_stadtlandfluss_answer_per_round_player'),
        ),
    ]
