# Generated by Django 6.0.5 on 2026-05-31 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_homewidget_widget_type_stadtlandflusslobby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFourGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vier gewinnt', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('board', models.JSONField(blank=True, default=list)),
                ('current_disc', models.CharField(choices=[('R', 'Rot'), ('Y', 'Gelb')], default='R', max_length=1)),
                ('winner_disc', models.CharField(blank=True, choices=[('R', 'Rot'), ('Y', 'Gelb')], max_length=1)),
                ('winning_line', models.JSONField(blank=True, default=list)),
                ('last_move', models.JSONField(blank=True, default=dict)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_connectfour_games', to=settings.AUTH_USER_MODEL)),
                ('player_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectfour_games_as_red', to=settings.AUTH_USER_MODEL)),
                ('player_yellow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectfour_games_as_yellow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vier gewinnt Spiel',
                'verbose_name_plural': 'Vier gewinnt Spiele',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectFourInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connectfour_invites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.connectfourgame')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connectfour_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vier gewinnt Einladung',
                'verbose_name_plural': 'Vier gewinnt Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='connectfourgame',
            index=models.Index(fields=['code'], name='app_connect_code_f5556a_idx'),
        ),
        migrations.AddIndex(
            model_name='connectfourgame',
            index=models.Index(fields=['owner', 'status'], name='app_connect_owner_i_f2d4de_idx'),
        ),
        migrations.AddIndex(
            model_name='connectfourgame',
            index=models.Index(fields=['player_red', 'status'], name='app_connect_player__72aa85_idx'),
        ),
        migrations.AddIndex(
            model_name='connectfourgame',
            index=models.Index(fields=['player_yellow', 'status'], name='app_connect_player__2226e5_idx'),
        ),
        migrations.AddIndex(
            model_name='connectfourinvite',
            index=models.Index(fields=['to_user', 'status'], name='app_connect_to_user_5a0c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='connectfourinvite',
            index=models.Index(fields=['game', 'status'], name='app_connect_game_id_25af24_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectfourinvite',
            constraint=models.UniqueConstraint(fields=('game', 'to_user'), name='unique_connectfour_invite_per_game_user'),
        ),
        migrations.AddConstraint(
            model_name='connectfourinvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='connectfour_invite_prevent_self'),
        ),
    ]
