# Generated by Django 6.0.5 on 2026-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_connectfourgame_connectfourinvite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawinggamelobby',
            name='status',
            field=models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('round_summary', 'Rundenübersicht'), ('finished', 'Beendet')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='stadtlandflusslobby',
            name='status',
            field=models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('round_summary', 'Rundenauswertung'), ('finished', 'Beendet')], default='waiting', max_length=20),
        ),
    ]
