# Generated by Django 6.0.5 on 2026-06-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_drawinggamelobby_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('clock', 'Uhr'), ('chat', 'Chats'), ('friends', 'Freunde'), ('skribble', 'Skribble'), ('tictactoe', 'Tic Tac Toe'), ('stadtlandfluss', 'Stadt Land Fluss'), ('uno', 'Uno')], default='weather', max_length=30),
        ),
        migrations.CreateModel(
            name='UnoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Uno', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'L\u00e4uft'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('draw_until_playable', models.BooleanField(default=False)),
                ('stacking', models.BooleanField(default=True)),
                ('jump_in', models.BooleanField(default=False)),
                ('seven_zero', models.BooleanField(default=False)),
                ('force_play_drawn_card', models.BooleanField(default=False)),
                ('keep_bluff_challenge', models.BooleanField(default=False)),
                ('deck', models.JSONField(blank=True, default=list)),
                ('discard_pile', models.JSONField(blank=True, default=list)),
                ('hands', models.JSONField(blank=True, default=dict)),
                ('current_color', models.CharField(blank=True, max_length=12)),
                ('current_player_index', models.PositiveSmallIntegerField(default=0)),
                ('direction', models.SmallIntegerField(default=1)),
                ('pending_draw', models.PositiveSmallIntegerField(default=0)),
                ('has_drawn_this_turn', models.BooleanField(default=False)),
                ('uno_calls', models.JSONField(blank=True, default=dict)),
                ('winner_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('action_log', models.JSONField(blank=True, default=list)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_uno_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uno Spiel',
                'verbose_name_plural': 'Uno Spiele',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UnoInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_uno_invites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.unogame')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_uno_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uno Einladung',
                'verbose_name_plural': 'Uno Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('seat', models.PositiveSmallIntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.unogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uno_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uno Spieler',
                'verbose_name_plural': 'Uno Spieler',
                'ordering': ['seat', 'joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unogame',
            index=models.Index(fields=['code'], name='app_unogame_code_1b03ce_idx'),
        ),
        migrations.AddIndex(
            model_name='unogame',
            index=models.Index(fields=['owner', 'status'], name='app_unogame_owner_i_b91350_idx'),
        ),
        migrations.AddIndex(
            model_name='unoinvite',
            index=models.Index(fields=['to_user', 'status'], name='app_unoinvi_to_user_dbee22_idx'),
        ),
        migrations.AddIndex(
            model_name='unoinvite',
            index=models.Index(fields=['game', 'status'], name='app_unoinvi_game_id_296758_idx'),
        ),
        migrations.AddConstraint(
            model_name='unoinvite',
            constraint=models.UniqueConstraint(fields=('game', 'to_user'), name='unique_uno_invite_per_game_user'),
        ),
        migrations.AddConstraint(
            model_name='unoinvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='uno_invite_prevent_self'),
        ),
        migrations.AddIndex(
            model_name='unoplayer',
            index=models.Index(fields=['game', 'seat'], name='app_unoplay_game_id_f9201a_idx'),
        ),
        migrations.AddIndex(
            model_name='unoplayer',
            index=models.Index(fields=['user', 'last_seen'], name='app_unoplay_user_id_df7f7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='unoplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_uno_player_per_game'),
        ),
        migrations.AddConstraint(
            model_name='unoplayer',
            constraint=models.UniqueConstraint(fields=('game', 'seat'), name='unique_uno_seat_per_game'),
        ),
    ]
