# Generated by Django 5.2.14 on 2026-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_homewidget_widget_type_unogame_unoinvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectfourgame',
            name='player_red_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectfourgame',
            name='player_yellow_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
