# Generated by Django 5.2.14 on 2026-06-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_connectfourgame_player_red_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleshipgame',
            name='player_a_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battleshipgame',
            name='player_b_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='player_o_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='player_x_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
