# Generated by Django 5.2.14 on 2026-06-03 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_battleshipgame_player_a_last_seen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hangman', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('word', models.CharField(blank=True, max_length=80)),
                ('word_hint', models.CharField(blank=True, max_length=120)),
                ('guessed_letters', models.JSONField(blank=True, default=list)),
                ('wrong_letters', models.JSONField(blank=True, default=list)),
                ('max_mistakes', models.PositiveSmallIntegerField(default=8)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('custom_words', models.TextField(blank=True)),
                ('last_guess', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hangman_lobbies', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_hangman_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hangman Lobby',
                'verbose_name_plural': 'Hangman Lobbys',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HangmanInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_hangman_invites', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_hangman_invites', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.hangmanlobby')),
            ],
            options={
                'verbose_name': 'Hangman Einladung',
                'verbose_name_plural': 'Hangman Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HangmanPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('score', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.hangmanlobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangman_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hangman Spieler',
                'verbose_name_plural': 'Hangman Spieler',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hangmanlobby',
            index=models.Index(fields=['code'], name='app_hangman_code_934f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='hangmanlobby',
            index=models.Index(fields=['owner', 'status'], name='app_hangman_owner_i_a69403_idx'),
        ),
        migrations.AddIndex(
            model_name='hangmaninvite',
            index=models.Index(fields=['to_user', 'status'], name='app_hangman_to_user_373a55_idx'),
        ),
        migrations.AddIndex(
            model_name='hangmaninvite',
            index=models.Index(fields=['lobby', 'status'], name='app_hangman_lobby_i_2ce653_idx'),
        ),
        migrations.AddConstraint(
            model_name='hangmaninvite',
            constraint=models.UniqueConstraint(fields=('lobby', 'to_user'), name='unique_hangman_invite_per_lobby_user'),
        ),
        migrations.AddConstraint(
            model_name='hangmaninvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='hangman_invite_prevent_self'),
        ),
        migrations.AddIndex(
            model_name='hangmanplayer',
            index=models.Index(fields=['lobby', 'last_seen'], name='app_hangman_lobby_i_801324_idx'),
        ),
        migrations.AddIndex(
            model_name='hangmanplayer',
            index=models.Index(fields=['user', 'last_seen'], name='app_hangman_user_id_dc3baa_idx'),
        ),
        migrations.AddConstraint(
            model_name='hangmanplayer',
            constraint=models.UniqueConstraint(fields=('lobby', 'user'), name='unique_hangman_player_per_lobby'),
        ),
    ]
