# Generated by Django 5.2.14 on 2026-06-04 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_hangmanlobby_hangmaninvite_hangmanplayer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gelöschte Benachrichtigung',
                'verbose_name_plural': 'gelöschte Benachrichtigungen',
                'indexes': [models.Index(fields=['user', 'key'], name='app_notific_user_id_74a486_idx'), models.Index(fields=['created_at'], name='app_notific_created_b2caff_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
