# Generated by Django 5.2.14 on 2026-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_notificationdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_badge_icon',
            field=models.CharField(default='fa-solid fa-star', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_badge_text',
            field=models.CharField(blank=True, default='MyTools', max_length=28),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_glow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_pattern',
            field=models.CharField(choices=[('none', 'Ohne Muster'), ('grid', 'Grid'), ('dots', 'Dots'), ('lines', 'Lines'), ('orbs', 'Orbs')], default='orbs', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_primary',
            field=models.CharField(default='#7c3aed', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_secondary',
            field=models.CharField(default='#06b6d4', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_style',
            field=models.CharField(choices=[('glass', 'Glass'), ('neon', 'Neon'), ('gamer', 'Gamer'), ('soft', 'Soft'), ('minimal', 'Minimal')], default='glass', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_text',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
