# Generated by Django 5.2.14 on 2026-06-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_userprofile_profile_card_badge_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_avatar_shape',
            field=models.CharField(choices=[('rounded', 'Abgerundet'), ('circle', 'Kreis'), ('square', 'Quadrat'), ('hex', 'Hexagon')], default='rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_badge_bg',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_border',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_gradient_angle',
            field=models.CharField(choices=[('45', 'Diagonal rechts'), ('90', 'Horizontal'), ('135', 'Diagonal links'), ('180', 'Vertikal'), ('225', 'Diagonal dunkel')], default='135', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_pattern_strength',
            field=models.CharField(choices=[('subtle', 'Dezent'), ('normal', 'Normal'), ('strong', 'Stark')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_radius',
            field=models.CharField(choices=[('soft', 'Leicht rund'), ('round', 'Rund'), ('bold', 'Sehr rund'), ('max', 'Maximal')], default='bold', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_shine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_tertiary',
            field=models.CharField(default='#c026d3', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_card_text_effect',
            field=models.CharField(choices=[('none', 'Normal'), ('shadow', 'Schatten'), ('glow', 'Glow'), ('outline', 'Outline')], default='shadow', max_length=20),
        ),
    ]
