# Generated by Django 5.2.14 on 2026-06-04 13:20

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_userprofile_profile_card_avatar_shape_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.file_share_upload_path)),
                ('original_name', models.CharField(max_length=180)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('token', models.CharField(max_length=48, unique=True)),
                ('is_public_link', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_file_shares', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_file_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dateifreigabe',
                'verbose_name_plural': 'Dateifreigaben',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='app_filesha_owner_i_a7986c_idx'), models.Index(fields=['token'], name='app_filesha_token_55a67e_idx'), models.Index(fields=['is_public_link', '-created_at'], name='app_filesha_is_publ_39bfda_idx')],
            },
        ),
    ]
