# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_fileshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="file_share_limit",
            field=models.CharField(
                choices=[
                    ("50", "50 MB"),
                    ("100", "100 MB"),
                    ("500", "500 MB"),
                    ("unlimited", "Unbegrenzt"),
                ],
                default="50",
                max_length=20,
                verbose_name="Datei-Share Upload-Limit",
            ),
        ),
    ]
