# Generated by Django 6.0.5 on 2026-06-05 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_userprofile_file_share_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('clock', 'Uhr'), ('chat', 'Chats'), ('friends', 'Freunde'), ('skribble', 'Skribble'), ('tictactoe', 'Tic Tac Toe'), ('stadtlandfluss', 'Stadt Land Fluss'), ('uno', 'Uno'), ('kniffel', 'Kniffel')], default='weather', max_length=30),
        ),
        migrations.CreateModel(
            name='KniffelGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kniffel', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('current_player_index', models.PositiveSmallIntegerField(default=0)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('roll_count', models.PositiveSmallIntegerField(default=0)),
                ('dice', models.JSONField(blank=True, default=list)),
                ('kept_indices', models.JSONField(blank=True, default=list)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('winner_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_log', models.JSONField(blank=True, default=list)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_kniffel_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kniffel Spiel',
                'verbose_name_plural': 'Kniffel Spiele',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KniffelInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_kniffel_invites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.kniffelgame')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_kniffel_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kniffel Einladung',
                'verbose_name_plural': 'Kniffel Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KniffelPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('seat', models.PositiveSmallIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.kniffelgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kniffel_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kniffel Spieler',
                'verbose_name_plural': 'Kniffel Spieler',
                'ordering': ['seat', 'joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kniffelgame',
            index=models.Index(fields=['code'], name='app_kniffel_code_f89bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='kniffelgame',
            index=models.Index(fields=['owner', 'status'], name='app_kniffel_owner_i_fdbe8f_idx'),
        ),
        migrations.AddIndex(
            model_name='kniffelinvite',
            index=models.Index(fields=['to_user', 'status'], name='app_kniffel_to_user_df6a59_idx'),
        ),
        migrations.AddIndex(
            model_name='kniffelinvite',
            index=models.Index(fields=['game', 'status'], name='app_kniffel_game_id_077bfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='kniffelinvite',
            constraint=models.UniqueConstraint(fields=('game', 'to_user'), name='unique_kniffel_invite_per_game_user'),
        ),
        migrations.AddConstraint(
            model_name='kniffelinvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='kniffel_invite_prevent_self'),
        ),
        migrations.AddIndex(
            model_name='kniffelplayer',
            index=models.Index(fields=['game', 'seat'], name='app_kniffel_game_id_3714e7_idx'),
        ),
        migrations.AddIndex(
            model_name='kniffelplayer',
            index=models.Index(fields=['user', 'last_seen'], name='app_kniffel_user_id_93ea7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='kniffelplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_kniffel_player_per_game'),
        ),
        migrations.AddConstraint(
            model_name='kniffelplayer',
            constraint=models.UniqueConstraint(fields=('game', 'seat'), name='unique_kniffel_seat_per_game'),
        ),
    ]
