# Generated by Django 6.0.5 on 2026-06-05 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_homewidget_widget_type_kniffelgame_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieClickerHighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('display_score', models.CharField(max_length=80)),
                ('cps', models.FloatField(default=0)),
                ('click_power', models.FloatField(default=0)),
                ('stardust', models.PositiveIntegerField(default=0)),
                ('ascensions', models.PositiveIntegerField(default=0)),
                ('achievements_count', models.PositiveSmallIntegerField(default=0)),
                ('upgrades_count', models.PositiveSmallIntegerField(default=0)),
                ('buildings_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_clicker_highscore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookie Cosmos Highscore',
                'verbose_name_plural': 'Cookie Cosmos Highscores',
                'indexes': [models.Index(fields=['-score', '-achieved_at'], name='app_cookiec_score_4beef8_idx')],
            },
        ),
    ]
