# Generated by Django 6.0.5 on 2026-06-06 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_cookieclickerhighscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in_rooms', to='app.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='theme',
            field=models.CharField(choices=[('default', 'Standard'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('grape', 'Grape'), ('graphite', 'Graphite')], default='default', max_length=20),
        ),
    ]
