# Generated by Django 6.0.5 on 2026-06-06 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_userprofile_profile_game_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erinnerung'),
        ),
        migrations.AddField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to=settings.AUTH_USER_MODEL, verbose_name='Geteilt mit'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_archived', '-updated_at'], name='app_note_user_id_7fd5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['reminder_at'], name='app_note_reminde_f81ff0_idx'),
        ),
    ]
