# Generated by Django 6.0.5 on 2026-06-07 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_note_reminder_at_note_shared_with_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_typing', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='app.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_typing_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat-Tippstatus',
                'verbose_name_plural': 'Chat-Tippstatus',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['room', 'is_typing', '-updated_at'], name='app_chattyp_room_id_792720_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_chat_typing_status')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('report_resolved', 'Meldung erledigt'), ('report_reopened', 'Meldung wieder geoeffnet'), ('feedback_status', 'Feedback-Status geaendert'), ('file_deleted', 'Datei-Freigabe geloescht'), ('user_suspended', 'Nutzer gesperrt'), ('user_unsuspended', 'Nutzersperre aufgehoben'), ('user_activated', 'Nutzer aktiviert'), ('user_deactivated', 'Nutzer deaktiviert')], max_length=40)),
                ('summary', models.CharField(max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderations-Audit-Log',
                'verbose_name_plural': 'Moderations-Audit-Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='app_moderat_action_bd020d_idx'), models.Index(fields=['target_user', '-created_at'], name='app_moderat_target__4321f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_suspensions', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_suspensions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzersperre',
                'verbose_name_plural': 'Nutzersperren',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'ends_at'], name='app_usersus_user_id_46f641_idx'), models.Index(fields=['ends_at'], name='app_usersus_ends_at_b269de_idx')],
            },
        ),
    ]
