# Generated by Django 5.2.14 on 2026-06-10 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_weatherlocation_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationauditlog',
            name='action',
            field=models.CharField(choices=[('report_resolved', 'Meldung erledigt'), ('report_reopened', 'Meldung wieder geoeffnet'), ('feedback_status', 'Feedback-Status geaendert'), ('file_deleted', 'Datei-Freigabe geloescht'), ('user_suspended', 'Nutzer gesperrt'), ('user_unsuspended', 'Nutzersperre aufgehoben'), ('user_activated', 'Nutzer aktiviert'), ('user_deactivated', 'Nutzer deaktiviert'), ('access_locked', 'Login und Registrierung gesperrt'), ('access_unlocked', 'Login und Registrierung entsperrt')], max_length=40),
        ),
        migrations.CreateModel(
            name='SiteAccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_registration_locked', models.BooleanField(default=False)),
                ('lock_message', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_access_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zugangs-Einstellung',
                'verbose_name_plural': 'Zugangs-Einstellungen',
            },
        ),
    ]
