# Generated by Django 5.2.14 on 2026-06-10 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_moderationauditlog_action_siteaccesssettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zwei-Faktor-Authentifizierung',
                'verbose_name_plural': 'Zwei-Faktor-Authentifizierungen',
            },
        ),
    ]
