# Generated by Django 5.2.15 on 2026-06-10 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_usertwofactorsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='active_game',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='active_game_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='active_game_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Game2048HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('best_tile', models.PositiveIntegerField(default=2)),
                ('moves', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_2048_highscore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2048 Highscore',
                'verbose_name_plural': '2048 Highscores',
                'indexes': [models.Index(fields=['-score', '-best_tile', '-achieved_at'], name='app_game204_score_9339e9_idx')],
            },
        ),
    ]
