# Generated by Django 5.2.15 on 2026-06-10 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_userpresence_active_game_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_left_last_seen', models.DateTimeField(blank=True, null=True)),
                ('player_right_last_seen', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Pong', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('playing', 'Läuft'), ('paused', 'Pausiert'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('target_score', models.PositiveSmallIntegerField(default=7)),
                ('score_left', models.PositiveSmallIntegerField(default=0)),
                ('score_right', models.PositiveSmallIntegerField(default=0)),
                ('paddle_left_y', models.FloatField(default=50)),
                ('paddle_right_y', models.FloatField(default=50)),
                ('ball_x', models.FloatField(default=50)),
                ('ball_y', models.FloatField(default=50)),
                ('ball_vx', models.FloatField(default=38)),
                ('ball_vy', models.FloatField(default=18)),
                ('winner_side', models.CharField(blank=True, choices=[('left', 'Links'), ('right', 'Rechts')], max_length=10)),
                ('last_hit_side', models.CharField(blank=True, choices=[('left', 'Links'), ('right', 'Rechts')], max_length=10)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('rally_hits', models.PositiveIntegerField(default=0)),
                ('best_rally', models.PositiveIntegerField(default=0)),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pong_games', to=settings.AUTH_USER_MODEL)),
                ('player_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pong_games_left', to=settings.AUTH_USER_MODEL)),
                ('player_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pong_games_right', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pong Spiel',
                'verbose_name_plural': 'Pong Spiele',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PongInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pong_invites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.ponggame')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pong_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pong Einladung',
                'verbose_name_plural': 'Pong Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ponggame',
            index=models.Index(fields=['code'], name='app_ponggam_code_62e8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ponggame',
            index=models.Index(fields=['owner', 'status'], name='app_ponggam_owner_i_24fec7_idx'),
        ),
        migrations.AddIndex(
            model_name='ponggame',
            index=models.Index(fields=['player_left', 'status'], name='app_ponggam_player__eec6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='ponggame',
            index=models.Index(fields=['player_right', 'status'], name='app_ponggam_player__84e9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='ponginvite',
            index=models.Index(fields=['to_user', 'status'], name='app_ponginv_to_user_5bab9f_idx'),
        ),
        migrations.AddIndex(
            model_name='ponginvite',
            index=models.Index(fields=['game', 'status'], name='app_ponginv_game_id_836856_idx'),
        ),
        migrations.AddConstraint(
            model_name='ponginvite',
            constraint=models.UniqueConstraint(fields=('game', 'to_user'), name='unique_pong_invite_per_game_user'),
        ),
        migrations.AddConstraint(
            model_name='ponginvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='pong_invite_prevent_self'),
        ),
    ]
