# Generated by Django 5.2.15 on 2026-06-11 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_moderationauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='battleshipgame',
            index=models.Index(fields=['status', '-updated_at'], name='bs_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['message', 'created_at'], name='chatattach_msg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'id'], name='chatmsg_room_id_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-created_at'], name='chatmsg_room_new_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by', '-updated_at'], name='chatroom_creator_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-updated_at'], name='chatroom_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroommember',
            index=models.Index(fields=['room', 'last_read_at'], name='chatmember_room_read_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroommember',
            index=models.Index(fields=['user', 'last_read_at'], name='chatmember_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='chattypingstatus',
            index=models.Index(fields=['room', 'user', '-updated_at'], name='typing_room_user_idx'),
        ),
        migrations.AddIndex(
            model_name='connectfourgame',
            index=models.Index(fields=['status', '-updated_at'], name='c4_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='drawinggameinvite',
            index=models.Index(fields=['to_user', 'status'], name='drawinvite_to_status_idx'),
        ),
        migrations.AddIndex(
            model_name='drawinggameinvite',
            index=models.Index(fields=['lobby', 'status'], name='drawinvite_lobby_status_idx'),
        ),
        migrations.AddIndex(
            model_name='drawinggamelobby',
            index=models.Index(fields=['status', '-updated_at'], name='draw_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='drawinggameplayer',
            index=models.Index(fields=['lobby', 'last_seen'], name='drawplayer_lobby_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='drawinggameplayer',
            index=models.Index(fields=['user', 'last_seen'], name='drawplayer_user_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['content_type', '-created_at'], name='fileshare_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hangmanlobby',
            index=models.Index(fields=['status', '-updated_at'], name='hang_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='homewidget',
            index=models.Index(fields=['user', 'is_enabled', 'order', 'created_at'], name='homewidget_enabled_order_idx'),
        ),
        migrations.AddIndex(
            model_name='kniffelgame',
            index=models.Index(fields=['status', '-updated_at'], name='kniffel_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='ponggame',
            index=models.Index(fields=['status', '-updated_at'], name='pong_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='profilegalleryimage',
            index=models.Index(fields=['user', 'is_public', '-created_at'], name='gallery_user_public_idx'),
        ),
        migrations.AddIndex(
            model_name='stadtlandflusslobby',
            index=models.Index(fields=['status', '-updated_at'], name='slf_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='stadtlandflussplayer',
            index=models.Index(fields=['lobby', 'last_seen'], name='slfplayer_lobby_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='stadtlandflussplayer',
            index=models.Index(fields=['user', 'last_seen'], name='slfplayer_user_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='tictactoegame',
            index=models.Index(fields=['status', '-updated_at'], name='ttt_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='unogame',
            index=models.Index(fields=['status', '-updated_at'], name='uno_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['active_game', '-active_game_updated_at'], name='upres_game_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherlocation',
            index=models.Index(fields=['user', 'is_default'], name='weather_user_default_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherlocation',
            index=models.Index(fields=['user', 'order', 'created_at'], name='weather_user_order_idx'),
        ),
    ]
