# Generated by Django 5.2.15 on 2026-06-12 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_battleshipgame_bs_status_updated_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('income', 'Einnahme'), ('expense', 'Ausgabe')], default='expense', max_length=20)),
                ('icon', models.CharField(default='fa-solid fa-wallet', max_length=80)),
                ('color', models.CharField(default='#2563eb', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget-Kategorie',
                'verbose_name_plural': 'Budget-Kategorien',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('income', 'Einnahme'), ('expense', 'Ausgabe')], default='expense', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('none', 'Einmalig'), ('monthly', 'Monatlich')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='app.budgetcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget-Buchung',
                'verbose_name_plural': 'Budget-Buchungen',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('planned_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expense_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings_goal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monatsbudget',
                'verbose_name_plural': 'Monatsbudgets',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['user', 'kind', 'name'], name='app_budgetc_user_id_17e14f_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'name'), name='unique_budget_category_per_user_kind'),
        ),
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['user', 'date'], name='app_budgete_user_id_2f31f1_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['user', 'entry_type', 'date'], name='app_budgete_user_id_347511_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['user', 'is_fixed', 'recurrence'], name='app_budgete_user_id_8be0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmonth',
            index=models.Index(fields=['user', 'year', 'month'], name='app_budgetm_user_id_93a1b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonth',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_budget_month_per_user'),
        ),
    ]
