# Generated by Django 5.2.15 on 2026-06-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_budgetcategory_budgetentry_budgetmonth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login erfolgreich'), ('login_failed', 'Login fehlgeschlagen'), ('logout', 'Logout'), ('two_factor_enabled', '2FA aktiviert'), ('two_factor_disabled', '2FA deaktiviert'), ('session_revoked', 'Sitzung beendet'), ('sessions_revoked', 'Andere Sitzungen beendet')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Erfolg'), ('warning', 'Warnung'), ('danger', 'Gefahr')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sicherheitsereignis',
                'verbose_name_plural': 'Sicherheitsereignisse',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_securit_user_id_afdd47_idx'), models.Index(fields=['event_type', '-created_at'], name='app_securit_event_t_ca151e_idx'), models.Index(fields=['session_key'], name='app_securit_session_a09686_idx')],
            },
        ),
    ]
