# Generated by Django 5.2.15 on 2026-06-12 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1800)),
                ('category', models.CharField(choices=[('tool', 'Tool'), ('game', 'Spiel'), ('design', 'Design / UI'), ('security', 'Sicherheit'), ('performance', 'Performance'), ('other', 'Sonstiges')], default='tool', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('normal', 'Normal'), ('high', 'Hoch')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('suggested', 'Vorgeschlagen'), ('planned', 'Geplant'), ('in_progress', 'In Arbeit'), ('done', 'Fertig'), ('rejected', 'Abgelehnt')], default='suggested', max_length=30)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature-Idee',
                'verbose_name_plural': 'Feature-Ideen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_comments', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.featureidea')),
            ],
            options={
                'verbose_name': 'Feature-Kommentar',
                'verbose_name_plural': 'Feature-Kommentare',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.featureidea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature-Vote',
                'verbose_name_plural': 'Feature-Votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='featureidea',
            index=models.Index(fields=['status', '-created_at'], name='app_feature_status_391e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='featureidea',
            index=models.Index(fields=['category', 'status', '-created_at'], name='app_feature_categor_ede63f_idx'),
        ),
        migrations.AddIndex(
            model_name='featureidea',
            index=models.Index(fields=['author', '-created_at'], name='app_feature_author__65cf13_idx'),
        ),
        migrations.AddIndex(
            model_name='featurecomment',
            index=models.Index(fields=['idea', 'created_at'], name='app_feature_idea_id_9909d8_idx'),
        ),
        migrations.AddIndex(
            model_name='featurecomment',
            index=models.Index(fields=['user', 'created_at'], name='app_feature_user_id_a80269_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevote',
            index=models.Index(fields=['idea', 'created_at'], name='app_feature_idea_id_c8cf11_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevote',
            index=models.Index(fields=['user', 'created_at'], name='app_feature_user_id_2b1e89_idx'),
        ),
        migrations.AddConstraint(
            model_name='featurevote',
            constraint=models.UniqueConstraint(fields=('idea', 'user'), name='unique_feature_vote_per_user'),
        ),
    ]
