# Generated by Django 5.2.15 on 2026-06-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_fileshare_expires_at_fileshare_max_downloads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCosmosV2Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_data', models.JSONField(blank=True, default=dict)),
                ('cookies', models.FloatField(default=0)),
                ('lifetime_cookies', models.FloatField(default=0)),
                ('cps', models.FloatField(default=0)),
                ('click_power', models.FloatField(default=1)),
                ('prestige_level', models.PositiveIntegerField(default=1)),
                ('prestige_crumbs', models.PositiveIntegerField(default=0)),
                ('achievements_count', models.PositiveSmallIntegerField(default=0)),
                ('upgrades_count', models.PositiveSmallIntegerField(default=0)),
                ('buildings_count', models.PositiveIntegerField(default=0)),
                ('last_manual_save', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_cosmos_v2_save', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookie Cosmos V2 Spielstand',
                'verbose_name_plural': 'Cookie Cosmos V2 Spielstände',
                'indexes': [models.Index(fields=['-prestige_level', '-lifetime_cookies'], name='app_cookiec_prestig_bbc262_idx'), models.Index(fields=['-updated_at'], name='app_cookiec_updated_f1b634_idx')],
            },
        ),
    ]
