# Generated by Django 5.2.15 on 2026-06-18 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_cookiecosmosv2save'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaccesssettings',
            name='tool_access_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='moderationauditlog',
            name='action',
            field=models.CharField(choices=[('report_resolved', 'Meldung erledigt'), ('report_reopened', 'Meldung wieder geoeffnet'), ('feedback_status', 'Feedback-Status geaendert'), ('file_deleted', 'Datei-Freigabe geloescht'), ('user_suspended', 'Nutzer gesperrt'), ('user_unsuspended', 'Nutzersperre aufgehoben'), ('user_activated', 'Nutzer aktiviert'), ('user_deactivated', 'Nutzer deaktiviert'), ('access_locked', 'Login und Registrierung gesperrt'), ('access_unlocked', 'Login und Registrierung entsperrt'), ('tool_access_updated', 'Tool-Zugriffe geaendert'), ('media_optimized', 'Medien komprimiert')], max_length=40),
        ),
        migrations.CreateModel(
            name='NebulaForgeTycoonSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_data', models.JSONField(blank=True, default=dict)),
                ('flux', models.FloatField(default=0)),
                ('lifetime_flux', models.FloatField(default=0)),
                ('total_lifetime_flux', models.FloatField(default=0)),
                ('cps', models.FloatField(default=0)),
                ('manual_power', models.FloatField(default=1)),
                ('prestige_level', models.PositiveIntegerField(default=1)),
                ('shards', models.PositiveIntegerField(default=0)),
                ('achievements_count', models.PositiveSmallIntegerField(default=0)),
                ('upgrades_count', models.PositiveSmallIntegerField(default=0)),
                ('buildings_count', models.PositiveIntegerField(default=0)),
                ('last_manual_save', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nebula_forge_tycoon_save', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nebula Forge Tycoon Spielstand',
                'verbose_name_plural': 'Nebula Forge Tycoon Spielstände',
                'indexes': [models.Index(fields=['-prestige_level', '-total_lifetime_flux'], name='app_nebulaf_prestig_20dbe6_idx'), models.Index(fields=['-updated_at'], name='app_nebulaf_updated_99f6bc_idx')],
            },
        ),
    ]
