# Generated by Django 5.2.15 on 2026-06-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_siteaccesssettings_tool_access_rules_and_more'),
        ('app', '0064_alter_moderationauditlog_action'),
    ]

    operations = [
    ]
