# Generated by Django 5.2.15 on 2026-06-18 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_merge_20260618_1334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WerewolfLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Werwolf-Dorf', max_length=80)),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'Öffentlich'), ('friends', 'Nur Freunde'), ('password', 'Privat mit Passwort')], default='public', max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('waiting', 'Wartet'), ('night', 'Nacht'), ('day', 'Tag'), ('finished', 'Beendet')], default='waiting', max_length=20)),
                ('max_players', models.PositiveSmallIntegerField(default=12)),
                ('werewolf_count', models.PositiveSmallIntegerField(default=2)),
                ('include_seer', models.BooleanField(default=True)),
                ('include_witch', models.BooleanField(default=True)),
                ('include_guard', models.BooleanField(default=True)),
                ('reveal_roles_on_death', models.BooleanField(default=True)),
                ('anonymous_day_votes', models.BooleanField(default=False)),
                ('day_number', models.PositiveSmallIntegerField(default=0)),
                ('winner', models.CharField(blank=True, max_length=20)),
                ('phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_werewolf_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Werwolf Lobby',
                'verbose_name_plural': 'Werwolf Lobbys',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WerewolfInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_werewolf_invites', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_werewolf_invites', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.werewolflobby')),
            ],
            options={
                'verbose_name': 'Werwolf Einladung',
                'verbose_name_plural': 'Werwolf Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WerewolfMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('village', 'Dorf'), ('wolves', 'Werwölfe'), ('system', 'System')], default='village', max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('day_number', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.werewolflobby')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werewolf_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Werwolf Nachricht',
                'verbose_name_plural': 'Werwolf Nachrichten',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WerewolfPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('seat', models.PositiveSmallIntegerField(default=0)),
                ('role', models.CharField(blank=True, choices=[('villager', 'Dorfbewohner'), ('werewolf', 'Werwolf'), ('seer', 'Seherin'), ('witch', 'Hexe'), ('guard', 'Beschützer')], max_length=20)),
                ('is_alive', models.BooleanField(default=True)),
                ('role_state', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.werewolflobby')),
                ('night_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_votes_received', to='app.werewolfplayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='werewolf_players', to=settings.AUTH_USER_MODEL)),
                ('vote_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_votes_received', to='app.werewolfplayer')),
            ],
            options={
                'verbose_name': 'Werwolf Spieler',
                'verbose_name_plural': 'Werwolf Spieler',
                'ordering': ['seat', 'joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='werewolflobby',
            index=models.Index(fields=['code'], name='app_werewol_code_2ff9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='werewolflobby',
            index=models.Index(fields=['visibility', 'status', '-updated_at'], name='wolf_public_status_idx'),
        ),
        migrations.AddIndex(
            model_name='werewolflobby',
            index=models.Index(fields=['owner', 'status'], name='wolf_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='werewolfinvite',
            index=models.Index(fields=['to_user', 'status'], name='wolfinvite_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='werewolfinvite',
            index=models.Index(fields=['lobby', 'status'], name='wolfinvite_lobby_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='werewolfinvite',
            constraint=models.UniqueConstraint(fields=('lobby', 'to_user'), name='unique_werewolf_invite_per_lobby_user'),
        ),
        migrations.AddConstraint(
            model_name='werewolfinvite',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='werewolf_invite_prevent_self'),
        ),
        migrations.AddIndex(
            model_name='werewolfmessage',
            index=models.Index(fields=['lobby', 'channel', 'created_at'], name='wolfmessage_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='werewolfplayer',
            index=models.Index(fields=['lobby', 'is_alive'], name='wolfplayer_alive_idx'),
        ),
        migrations.AddIndex(
            model_name='werewolfplayer',
            index=models.Index(fields=['user', 'last_seen'], name='wolfplayer_user_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='werewolfplayer',
            constraint=models.UniqueConstraint(fields=('lobby', 'user'), name='unique_werewolf_player_per_lobby'),
        ),
    ]
