# Generated by Django 5.2.15 on 2026-06-19 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_merge_20260618_1334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('clock', 'Uhr'), ('chat', 'Chats'), ('friends', 'Freunde'), ('budget', 'Budget'), ('file_share', 'Datei-Share'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('cookie_clicker', 'Cookie Cosmos'), ('cookie_cosmos_v2', 'Cookie Cosmos V2'), ('nebula_forge_tycoon', 'Nebula Forge Tycoon'), ('game_2048', '2048'), ('skribble', 'Skribble'), ('tictactoe', 'Tic Tac Toe'), ('connectfour', 'Vier gewinnt'), ('battleship', 'Schiffe versenken'), ('hangman', 'Hangman'), ('stadtlandfluss', 'Stadt Land Fluss'), ('uno', 'Uno'), ('kniffel', 'Kniffel'), ('pong', 'Pong')], default='weather', max_length=30),
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web-Push-Abo',
                'verbose_name_plural': 'Web-Push-Abos',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active', '-last_seen_at'], name='app_webpush_user_id_b0c45f_idx'), models.Index(fields=['is_active', '-last_seen_at'], name='app_webpush_is_acti_10947d_idx')],
            },
        ),
    ]
