# Generated by Django 5.2.15 on 2026-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_userprofile_privacy_show_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='color',
            field=models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('purple', 'Lila'), ('orange', 'Orange'), ('red', 'Rot')], default='blue', max_length=20),
        ),
    ]
