# Generated by Django 5.2.15 on 2026-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_userprofile_privacy_show_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='widget_type',
            field=models.CharField(choices=[('weather', 'Wetter'), ('notes', 'Notizen'), ('benchmark', 'Human Benchmark'), ('stats', 'Schnellstatistiken'), ('clock', 'Uhr'), ('chat', 'Chats'), ('friends', 'Freunde'), ('skribble', 'Skribble'), ('tictactoe', 'Tic Tac Toe'), ('stadtlandfluss', 'Stadt Land Fluss'), ('uno', 'Uno'), ('kniffel', 'Kniffel'), ('file_share', 'Datei-Share'), ('budget', 'Budget'), ('favorites', 'Favoriten'), ('roadmap', 'Roadmap'), ('inbox', 'Inbox'), ('changelog', 'Changelog')], default='weather', max_length=30),
        ),
    ]
