# Generated by Codex on 2026-06-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_add_home_widget_types"),
        ("app", "0071_shortcut_color"),
    ]

    operations = []
