# Generated by Codex on 2026-06-26

from django.db import migrations, models


COLOR_CHOICES = [
    ("blue", "Blau"),
    ("green", "Grün"),
    ("purple", "Lila"),
    ("orange", "Orange"),
    ("red", "Rot"),
    ("theme", "Design"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_merge_home_widget_types_shortcut_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homewidget",
            name="color",
            field=models.CharField(choices=COLOR_CHOICES, default="blue", max_length=20),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="color",
            field=models.CharField(choices=COLOR_CHOICES, default="blue", max_length=20),
        ),
        migrations.AlterField(
            model_name="shortcutsection",
            name="color",
            field=models.CharField(choices=COLOR_CHOICES, default="blue", max_length=20),
        ),
    ]
