# Generated by Django 5.2.15 on 2026-06-27 13:18

from django.db import migrations, models


def use_theme_for_existing_blue_home_colors(apps, schema_editor):
    HomeWidget = apps.get_model('app', 'HomeWidget')
    Shortcut = apps.get_model('app', 'Shortcut')
    ShortcutSection = apps.get_model('app', 'ShortcutSection')

    HomeWidget.objects.filter(color='blue').update(color='theme')
    Shortcut.objects.filter(color='blue').update(color='theme')
    ShortcutSection.objects.filter(name='Verknüpfungen', color='blue').update(color='theme')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_add_theme_color_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='color',
            field=models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('purple', 'Lila'), ('orange', 'Orange'), ('red', 'Rot'), ('theme', 'Design')], default='theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='color',
            field=models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('purple', 'Lila'), ('orange', 'Orange'), ('red', 'Rot'), ('theme', 'Design')], default='theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortcutsection',
            name='color',
            field=models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('purple', 'Lila'), ('orange', 'Orange'), ('red', 'Rot'), ('theme', 'Design')], default='theme', max_length=20),
        ),
        migrations.RunPython(use_theme_for_existing_blue_home_colors, migrations.RunPython.noop),
    ]
