# Generated by Django 5.2.15 on 2026-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_default_theme_home_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanbenchmarkhighscore',
            name='game',
            field=models.CharField(choices=[('reaction', 'Reaktion'), ('aim', 'Zieltrainer'), ('typing', 'Tipptest'), ('visual', 'Visuelles Gedächtnis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='humanbenchmarkscore',
            name='game',
            field=models.CharField(choices=[('reaction', 'Reaktion'), ('aim', 'Zieltrainer'), ('typing', 'Tipptest'), ('visual', 'Visuelles Gedächtnis')], max_length=20),
        ),
    ]
