# Generated by Django 5.2.15 on 2026-07-01 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_alter_humanbenchmarkhighscore_game_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeHighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_key', models.CharField(max_length=80)),
                ('score', models.PositiveIntegerField(default=0)),
                ('length', models.PositiveIntegerField(default=3)),
                ('fruits', models.PositiveIntegerField(default=0)),
                ('moves', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=1)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snake_highscores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snake Highscore',
                'verbose_name_plural': 'Snake Highscores',
                'indexes': [models.Index(fields=['-score', '-length', '-achieved_at'], name='app_snakehi_score_7077c3_idx'), models.Index(fields=['user', '-score'], name='app_snakehi_user_id_6e275f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'settings_key'), name='unique_snake_highscore_per_user_settings')],
            },
        ),
    ]
