# Generated by Django 5.2.15 on 2026-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_snakehighscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewidget',
            name='color',
            field=models.CharField(choices=[('theme', 'Design'), ('blue', 'Blau'), ('cyan', 'Cyan'), ('teal', 'Türkis'), ('green', 'Grün'), ('yellow', 'Gelb'), ('orange', 'Orange'), ('red', 'Rot'), ('pink', 'Pink'), ('purple', 'Lila'), ('indigo', 'Indigo'), ('gray', 'Grau')], default='theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='color',
            field=models.CharField(choices=[('theme', 'Design'), ('blue', 'Blau'), ('cyan', 'Cyan'), ('teal', 'Türkis'), ('green', 'Grün'), ('yellow', 'Gelb'), ('orange', 'Orange'), ('red', 'Rot'), ('pink', 'Pink'), ('purple', 'Lila'), ('indigo', 'Indigo'), ('gray', 'Grau')], default='theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortcutsection',
            name='color',
            field=models.CharField(choices=[('theme', 'Design'), ('blue', 'Blau'), ('cyan', 'Cyan'), ('teal', 'Türkis'), ('green', 'Grün'), ('yellow', 'Gelb'), ('orange', 'Orange'), ('red', 'Rot'), ('pink', 'Pink'), ('purple', 'Lila'), ('indigo', 'Indigo'), ('gray', 'Grau')], default='theme', max_length=20),
        ),
    ]
