from django.utils.translation import gettext_lazy as _

from .models import SiteAccessSettings


ACCESS_CONTROL_ITEMS = (
    {
        "key": "chat",
        "label": _("Chat"),
        "kind": _("Tool"),
        "category": _("Kommunikation"),
        "icon": "fa-solid fa-comments",
        "url_names": (
            "chat",
            "chat_room",
            "chat_direct",
            "chat_group_create",
            "chat_group_settings",
            "chat_group_leave",
            "chat_group_member_action",
            "chat_send",
            "chat_message_delete",
            "chat_message_edit",
            "chat_message_pin",
            "chat_message_react",
            "chat_theme",
            "chat_messages_api",
            "chat_typing_api",
        ),
    },
    {
        "key": "users",
        "label": _("Nutzer"),
        "kind": _("Tool"),
        "category": _("Kommunikation"),
        "icon": "fa-solid fa-users",
        "url_names": (
            "users",
            "public_profile",
            "friends_list",
            "friendship_action",
            "block_user",
            "report_user",
        ),
    },
    {
        "key": "notes",
        "label": _("Notizen"),
        "kind": _("Tool"),
        "category": _("Alltag"),
        "icon": "fa-regular fa-note-sticky",
        "url_names": (
            "notes",
            "note_create",
            "note_detail",
            "note_edit",
            "note_delete",
            "note_toggle_pin",
            "note_toggle_archive",
        ),
    },
    {
        "key": "clock",
        "label": _("Uhr"),
        "kind": _("Tool"),
        "category": _("Alltag"),
        "icon": "fa-regular fa-clock",
        "url_names": ("clock",),
    },
    {
        "key": "file_share",
        "label": _("Datei-Share"),
        "kind": _("Tool"),
        "category": _("Alltag"),
        "icon": "fa-solid fa-share-nodes",
        "url_names": ("file_share", "file_share_upload", "file_share_delete"),
    },
    {
        "key": "feedback",
        "label": _("Feedback"),
        "kind": _("Tool"),
        "category": _("Alltag"),
        "icon": "fa-solid fa-comment-dots",
        "url_names": ("feedback",),
    },
    {
        "key": "roadmap",
        "label": _("Roadmap"),
        "kind": _("Tool"),
        "category": _("Alltag"),
        "icon": "fa-solid fa-route",
        "url_names": ("roadmap",),
    },
    {
        "key": "achievement_center",
        "label": _("Achievement-Center"),
        "kind": _("Tool"),
        "category": _("Profil"),
        "icon": "fa-solid fa-trophy",
        "url_names": ("achievement_center",),
    },
    {
        "key": "weather",
        "label": _("Wetter"),
        "kind": _("Tool"),
        "category": _("Alltag"),
        "icon": "fa-solid fa-cloud-sun",
        "url_names": ("weather", "weather_icon"),
    },
    {
        "key": "calculator",
        "label": _("Rechner"),
        "kind": _("Tool"),
        "category": _("Rechner & Helfer"),
        "icon": "fa-solid fa-square-root-variable",
        "url_names": ("calculator",),
    },
    {
        "key": "spritkosten",
        "label": _("Spritkosten"),
        "kind": _("Tool"),
        "category": _("Rechner & Helfer"),
        "icon": "fa-solid fa-gas-pump",
        "url_names": ("spritkostenrechner", "tankstellen-api"),
    },
    {
        "key": "budget_tracker",
        "label": _("Budget-Tracker"),
        "kind": _("Tool"),
        "category": _("Rechner & Helfer"),
        "icon": "fa-solid fa-wallet",
        "url_names": ("budget_tracker", "budget_tracker_export"),
    },
    {
        "key": "unit_converter",
        "label": _("Einheitenrechner"),
        "kind": _("Tool"),
        "category": _("Rechner & Helfer"),
        "icon": "fa-solid fa-calculator",
        "url_names": ("unit_converter",),
    },
    {
        "key": "randomizer_tools",
        "label": _("Randomizer"),
        "kind": _("Tool"),
        "category": _("Rechner & Helfer"),
        "icon": "fa-solid fa-shuffle",
        "url_names": ("randomizer_tools",),
    },
    {
        "key": "qr_code_tool",
        "label": _("QR-Code Tool"),
        "kind": _("Tool"),
        "category": _("Rechner & Helfer"),
        "icon": "fa-solid fa-qrcode",
        "url_names": ("qr_code_tool",),
    },
    {
        "key": "genius_search",
        "label": _("Genius Search"),
        "kind": _("Tool"),
        "category": _("Medien & Design"),
        "icon": "fa-solid fa-music",
        "url_names": ("genius-search", "genius-search-api"),
    },
    {
        "key": "image_tools",
        "label": _("Bild Tools"),
        "kind": _("Tool"),
        "category": _("Medien & Design"),
        "icon": "fa-regular fa-image",
        "url_names": ("image_tools",),
    },
    {
        "key": "file_converter",
        "label": _("Datei-Konverter"),
        "kind": _("Tool"),
        "category": _("Medien & Design"),
        "icon": "fa-solid fa-file-arrow-down",
        "url_names": ("file_converter",),
    },
    {
        "key": "color_palette_tool",
        "label": _("Color Palette"),
        "kind": _("Tool"),
        "category": _("Medien & Design"),
        "icon": "fa-solid fa-eye-dropper",
        "url_names": ("color_palette_tool",),
    },
    {
        "key": "profile_card_designer",
        "label": _("Profilkarten-Designer"),
        "kind": _("Tool"),
        "category": _("Medien & Design"),
        "icon": "fa-solid fa-id-card-clip",
        "url_names": ("profile_card_designer",),
    },
    {
        "key": "avatar_wiki",
        "label": _("Avatar Wiki"),
        "kind": _("Tool"),
        "category": _("Medien & Design"),
        "icon": "fa-solid fa-wind",
        "url_names": ("avatar-wiki", "avatar-characters-api", "avatar-character-detail-api"),
    },
    {
        "key": "stream_deck",
        "label": _("Stream Deck"),
        "kind": _("Tool"),
        "category": _("Streaming"),
        "icon": "fa-solid fa-table-cells-large",
        "url_names": ("stream-deck", "stream-deck-voicemod-action"),
    },
    {
        "key": "obs_dashboard",
        "label": _("OBS Dashboard"),
        "kind": _("Tool"),
        "category": _("Streaming"),
        "icon": "fa-solid fa-display",
        "url_names": ("obs-dashboard",),
    },
    {
        "key": "leaderboard",
        "label": _("Leaderboard"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-trophy",
        "url_names": ("leaderboard",),
    },
    {
        "key": "human_benchmark",
        "label": _("Human Benchmark"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-stopwatch",
        "url_names": ("human-benchmark", "human-benchmark-score-api"),
    },
    {
        "key": "drift_circuit",
        "label": _("Racing Game"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-car-side",
        "url_names": ("drift-circuit",),
    },
    {
        "key": "game_2048",
        "label": _("2048"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-table-cells-large",
        "url_names": ("game-2048", "game-2048-score-api", "game-2048-activity-api"),
    },
    {
        "key": "snake_powerups",
        "label": _("Snake Powerups"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-staff-snake",
        "url_names": ("snake-powerups",),
    },
    {
        "key": "cookie_clicker",
        "label": _("Cookie Cosmos"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-cookie-bite",
        "url_names": ("cookie-clicker", "cookie-clicker-score-api"),
    },
    {
        "key": "cookie_cosmos_v2",
        "label": _("Cookie Cosmos V2"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-cookie-bite",
        "url_names": ("cookie-cosmos-v2", "cookie-cosmos-v2-load-api", "cookie-cosmos-v2-save-api"),
    },
    {
        "key": "nebula_forge_tycoon",
        "label": _("Nebula Forge Tycoon"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-meteor",
        "url_names": (
            "nebula-forge-tycoon",
            "nebula-forge-tycoon-load-api",
            "nebula-forge-tycoon-save-api",
        ),
    },
    {
        "key": "tictactoe",
        "label": _("Tic Tac Toe"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-table-cells",
        "url_names": (
            "tictactoe_home",
            "tictactoe_lobby",
            "tictactoe_invite_friend",
            "tictactoe_invite_response",
            "tictactoe_leave",
            "tictactoe_delete",
            "tictactoe_state_api",
            "tictactoe_home_state_api",
            "tictactoe_move_api",
            "tictactoe_reset_api",
        ),
    },
    {
        "key": "connectfour",
        "label": _("Vier gewinnt"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-grip",
        "url_names": (
            "connectfour_home",
            "connectfour_lobby",
            "connectfour_invite_friend",
            "connectfour_invite_response",
            "connectfour_leave",
            "connectfour_delete",
            "connectfour_home_state_api",
            "connectfour_state_api",
            "connectfour_move_api",
            "connectfour_reset_api",
        ),
    },
    {
        "key": "battleship",
        "label": _("Schiffe versenken"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-anchor",
        "url_names": (
            "battleship_home",
            "battleship_lobby",
            "battleship_invite_friend",
            "battleship_invite_response",
            "battleship_leave",
            "battleship_delete",
            "battleship_home_state_api",
            "battleship_state_api",
            "battleship_place_api",
            "battleship_attack_api",
            "battleship_reset_api",
        ),
    },
    {
        "key": "stadtlandfluss",
        "label": _("Stadt Land Fluss"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-pen-to-square",
        "url_names": (
            "stadtlandfluss_home",
            "stadtlandfluss_lobby",
            "stadtlandfluss_invite_friend",
            "stadtlandfluss_invite_response",
            "stadtlandfluss_start",
            "stadtlandfluss_continue",
            "stadtlandfluss_restart",
            "stadtlandfluss_leave",
            "stadtlandfluss_delete",
            "stadtlandfluss_home_state_api",
            "stadtlandfluss_state_api",
            "stadtlandfluss_draft_api",
            "stadtlandfluss_submit_api",
            "stadtlandfluss_vote_api",
        ),
    },
    {
        "key": "hangman",
        "label": _("Hangman"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-user-secret",
        "url_names": (
            "hangman_home",
            "hangman_lobby",
            "hangman_invite_friend",
            "hangman_invite_response",
            "hangman_leave",
            "hangman_delete",
            "hangman_home_state_api",
            "hangman_state_api",
            "hangman_start_api",
            "hangman_word_api",
            "hangman_guess_api",
            "hangman_review_api",
            "hangman_reset_api",
        ),
    },
    {
        "key": "uno",
        "label": _("Uno"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-layer-group",
        "url_names": (
            "uno_home",
            "uno_lobby",
            "uno_invite_friend",
            "uno_invite_response",
            "uno_leave",
            "uno_delete",
            "uno_home_state_api",
            "uno_state_api",
            "uno_start_api",
            "uno_play_api",
            "uno_draw_api",
            "uno_pass_api",
            "uno_call_api",
            "uno_catch_api",
            "uno_reset_api",
        ),
    },
    {
        "key": "kniffel",
        "label": _("Kniffel"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-dice",
        "url_names": (
            "kniffel_home",
            "kniffel_lobby",
            "kniffel_invite_friend",
            "kniffel_invite_response",
            "kniffel_leave",
            "kniffel_delete",
            "kniffel_home_state_api",
            "kniffel_state_api",
            "kniffel_start_api",
            "kniffel_roll_api",
            "kniffel_score_api",
            "kniffel_reset_api",
        ),
    },
    {
        "key": "pong",
        "label": _("Pong"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-table-tennis-paddle-ball",
        "url_names": (
            "pong_home",
            "pong_lobby",
            "pong_invite_friend",
            "pong_invite_response",
            "pong_leave",
            "pong_delete",
            "pong_home_state_api",
            "pong_state_api",
            "pong_paddle_api",
            "pong_reset_api",
        ),
    },
    {
        "key": "skribble",
        "label": _("Skribble"),
        "kind": _("Spiel"),
        "category": _("Spiele"),
        "icon": "fa-solid fa-pencil",
        "url_names": (
            "skribble_home",
            "skribble_lobby",
            "skribble_invite_friend",
            "skribble_invite_response",
            "skribble_update_avatar",
            "skribble_start",
            "skribble_restart",
            "skribble_continue_round",
            "skribble_leave_lobby",
            "skribble_delete_lobby",
            "skribble_state_api",
            "skribble_choose_word_api",
            "skribble_draw_api",
            "skribble_guess_api",
        ),
    },
)


ACCESS_URL_NAME_TO_KEY = {
    url_name: item["key"]
    for item in ACCESS_CONTROL_ITEMS
    for url_name in item["url_names"]
}

ACCESS_ITEM_BY_KEY = {item["key"]: item for item in ACCESS_CONTROL_ITEMS}
ACCESS_CONTROL_KEYS = tuple(item["key"] for item in ACCESS_CONTROL_ITEMS)


def access_key_for_url_name(url_name):
    return ACCESS_URL_NAME_TO_KEY.get(url_name)


def user_can_access_key(user, key, access_settings=None):
    access_settings = access_settings or SiteAccessSettings.get_solo()
    level = access_settings.get_tool_access_level(key)
    if level == SiteAccessSettings.TOOL_ACCESS_ALL:
        return True
    if level == SiteAccessSettings.TOOL_ACCESS_ADMIN:
        return bool(getattr(user, "is_active", False) and getattr(user, "is_staff", False))
    return False


def get_access_control_items(access_settings=None):
    access_settings = access_settings or SiteAccessSettings.get_solo()
    items = []
    for item in ACCESS_CONTROL_ITEMS:
        entry = dict(item)
        entry["access_level"] = access_settings.get_tool_access_level(item["key"])
        items.append(entry)
    return items
