from django.urls import path

from .auth_views import two_factor_settings_view, two_factor_verify_view

from .views import (
    about,
    avatar_character_detail_api,
    avatar_characters_api,
    avatar_wiki,
    clock_view,
    calculator_view,
    color_palette_tool_view,
    cookie_clicker,
    cookie_clicker_score_api,
    game_2048,
    game_2048_activity_api,
    game_2048_score_api,
    drift_circuit,
    genius_search,
    genius_search_api,
    home,
    human_benchmark,
    human_benchmark_score_api,
    note_create_view,
    note_delete_view,
    note_detail_view,
    note_edit_view,
    note_toggle_archive_view,
    note_toggle_pin_view,
    notes_view,
    obs_dashboard,
    signup,
    spritkostenrechner,
    stream_deck,
    tankstellen_api,
    unit_converter_view,
    randomizer_tools_view,
    snake_powerups,
    weather,
    weather_icon_view,
    pwa_manifest_view,
    pwa_service_worker_view,
    offline_view,
)
from .profile_views import (
    block_user_view,
    delete_gallery_image_view,
    friends_list_view,
    friendship_action_view,
    profile_gallery_upload_view,
    profile_card_designer_view,
    profile_view,
    report_user_view,
    public_profile_view,
    user_presence_api,
    users_view,
)
from .skribble_views import (
    skribble_choose_word_api,
    skribble_continue_round,
    skribble_delete_lobby,
    skribble_draw_api,
    skribble_guess_api,
    skribble_home,
    skribble_invite_friend,
    skribble_invite_response,
    skribble_leave_lobby,
    skribble_lobby,
    skribble_restart,
    skribble_start,
    skribble_state_api,
    skribble_update_avatar,
)
from .tictactoe_views import (
    tictactoe_home,
    tictactoe_delete,
    tictactoe_invite_friend,
    tictactoe_invite_response,
    tictactoe_leave,
    tictactoe_lobby,
    tictactoe_home_state_api,
    tictactoe_move_api,
    tictactoe_reset_api,
    tictactoe_state_api,
)
from .connectfour_views import (
    connectfour_delete,
    connectfour_home,
    connectfour_home_state_api,
    connectfour_invite_friend,
    connectfour_invite_response,
    connectfour_leave,
    connectfour_lobby,
    connectfour_move_api,
    connectfour_reset_api,
    connectfour_state_api,
)
from .battleship_views import (
    battleship_attack_api,
    battleship_delete,
    battleship_home,
    battleship_home_state_api,
    battleship_invite_friend,
    battleship_invite_response,
    battleship_leave,
    battleship_lobby,
    battleship_place_api,
    battleship_reset_api,
    battleship_state_api,
)
from .stadtlandfluss_views import (
    stadtlandfluss_continue,
    stadtlandfluss_delete,
    stadtlandfluss_draft_api,
    stadtlandfluss_home,
    stadtlandfluss_invite_friend,
    stadtlandfluss_invite_response,
    stadtlandfluss_leave,
    stadtlandfluss_lobby,
    stadtlandfluss_home_state_api,
    stadtlandfluss_restart,
    stadtlandfluss_start,
    stadtlandfluss_state_api,
    stadtlandfluss_submit_api,
    stadtlandfluss_vote_api,
)
from .hangman_views import (
    hangman_delete,
    hangman_guess_api,
    hangman_home,
    hangman_home_state_api,
    hangman_invite_friend,
    hangman_invite_response,
    hangman_leave,
    hangman_lobby,
    hangman_reset_api,
    hangman_review_api,
    hangman_start_api,
    hangman_state_api,
    hangman_word_api,
)
from .uno_views import (
    uno_call_api,
    uno_catch_api,
    uno_delete,
    uno_draw_api,
    uno_home,
    uno_home_state_api,
    uno_invite_friend,
    uno_invite_response,
    uno_leave,
    uno_lobby,
    uno_pass_api,
    uno_play_api,
    uno_reset_api,
    uno_start_api,
    uno_state_api,
)
from .kniffel_views import (
    kniffel_delete,
    kniffel_home,
    kniffel_home_state_api,
    kniffel_invite_friend,
    kniffel_invite_response,
    kniffel_leave,
    kniffel_lobby,
    kniffel_reset_api,
    kniffel_roll_api,
    kniffel_score_api,
    kniffel_start_api,
    kniffel_state_api,
)
from .pong_views import (
    pong_delete,
    pong_home,
    pong_home_state_api,
    pong_invite_friend,
    pong_invite_response,
    pong_leave,
    pong_lobby,
    pong_paddle_api,
    pong_reset_api,
    pong_state_api,
)
from .chat_views import (
    chat_group_leave_view,
    chat_group_member_action_view,
    chat_group_settings_view,
    chat_messages_api,
    chat_typing_api,
    chat_view,
    create_group_chat,
    delete_chat_message,
    edit_chat_message,
    pin_chat_message,
    react_chat_message,
    send_chat_message,
    set_chat_theme,
    start_direct_chat,
)
from .notification_views import live_status_api, notification_center_api, notification_counts_api, notification_dismiss_all_api, notification_dismiss_api

from .budget_views import (
    budget_tracker_export_csv,
    budget_tracker_view,
)
from .performance_tools_views import (
    file_share_delete_view,
    file_share_download_view,
    file_share_upload_view,
    file_share_view,
    image_tools_view,
    leaderboard_view,
)
from .platform_views import (
    favorite_toggle_view,
    favorites_view,
    feedback_view,
    global_search_api,
    inbox_mark_read_view,
    inbox_view,
)
from .security_views import qr_code_tool_view, security_dashboard_view
from .community_views import achievement_center_view, changelog_view, roadmap_view, server_status_view
from .moderation_views import (
    moderation_access_toggle_view,
    moderation_dashboard_view,
    moderation_feedback_status_view,
    moderation_file_share_delete_view,
    moderation_media_optimize_view,
    moderation_report_action_view,
    moderation_user_status_view,
)

urlpatterns = [
    path('manifest.webmanifest', pwa_manifest_view, name='pwa_manifest'),
    path('service-worker.js', pwa_service_worker_view, name='pwa_service_worker'),
    path('offline/', offline_view, name='offline'),
    path('color-palette/', color_palette_tool_view, name='color_palette_tool'),
    path('signup/', signup, name='signup'),
    path('accounts/2fa/', two_factor_verify_view, name='two_factor_verify'),
    path('settings/security/2fa/', two_factor_settings_view, name='two_factor_settings'),
    path('security/', security_dashboard_view, name='security_dashboard'),
    path('', home, name='home'),
    path('home/', home, name='home'),
    path('about/', about, name='about'),
    path('favorites/', favorites_view, name='favorites'),
    path('favorites/<slug:tool_key>/toggle/', favorite_toggle_view, name='favorite_toggle'),
    path('api/search/', global_search_api, name='global_search_api'),
    path('inbox/', inbox_view, name='inbox'),
    path('inbox/read/', inbox_mark_read_view, name='inbox_mark_read'),
    path('feedback/', feedback_view, name='feedback'),
    path('roadmap/', roadmap_view, name='roadmap'),
    path('changelog/', changelog_view, name='changelog'),
    path('achievements/', achievement_center_view, name='achievement_center'),
    path('server-status/', server_status_view, name='server_status'),
    path('moderation/', moderation_dashboard_view, name='moderation'),
    path('moderation/access/', moderation_access_toggle_view, name='moderation_access_toggle'),
    path('moderation/reports/<int:report_id>/', moderation_report_action_view, name='moderation_report_action'),
    path('moderation/feedback/<int:feedback_id>/status/', moderation_feedback_status_view, name='moderation_feedback_status'),
    path('moderation/file-shares/<int:share_id>/delete/', moderation_file_share_delete_view, name='moderation_file_share_delete'),
    path('moderation/media/optimize/', moderation_media_optimize_view, name='moderation_media_optimize'),
    path('moderation/users/<int:user_id>/status/', moderation_user_status_view, name='moderation_user_status'),

    path('leaderboard/', leaderboard_view, name='leaderboard'),
    path('bild-tools/', image_tools_view, name='image_tools'),
    path('datei-share/', file_share_view, name='file_share'),
    path('datei-share/upload/', file_share_upload_view, name='file_share_upload'),
    path('datei-share/<str:token>/download/', file_share_download_view, name='file_share_download'),
    path('datei-share/<int:share_id>/delete/', file_share_delete_view, name='file_share_delete'),
    path('uhr/', clock_view, name='clock'),

    path('profile/', profile_view, name='profile'),
    path('profile/card-designer/', profile_card_designer_view, name='profile_card_designer'),
    path('profile/gallery/upload/', profile_gallery_upload_view, name='profile_gallery_upload'),
    path('profile/gallery/<int:image_id>/delete/', delete_gallery_image_view, name='profile_gallery_delete'),
    path('users/', users_view, name='users'),
    path('users/<int:user_id>/', public_profile_view, name='public_profile'),
    path('users/<int:user_id>/friends/', friends_list_view, name='friends_list'),
    path('users/<int:user_id>/friendship/', friendship_action_view, name='friendship_action'),
    path('users/<int:user_id>/block/', block_user_view, name='block_user'),
    path('users/<int:user_id>/report/', report_user_view, name='report_user'),

    path('chat/', chat_view, name='chat'),
    path('chat/<int:room_id>/', chat_view, name='chat_room'),
    path('chat/direct/<int:user_id>/', start_direct_chat, name='chat_direct'),
    path('chat/group/new/', create_group_chat, name='chat_group_create'),
    path('chat/<int:room_id>/group/settings/', chat_group_settings_view, name='chat_group_settings'),
    path('chat/<int:room_id>/group/leave/', chat_group_leave_view, name='chat_group_leave'),
    path('chat/<int:room_id>/group/member/<int:user_id>/', chat_group_member_action_view, name='chat_group_member_action'),
    path('chat/<int:room_id>/send/', send_chat_message, name='chat_send'),
    path('chat/<int:room_id>/message/<int:message_id>/delete/', delete_chat_message, name='chat_message_delete'),
    path('chat/<int:room_id>/message/<int:message_id>/edit/', edit_chat_message, name='chat_message_edit'),
    path('chat/<int:room_id>/message/<int:message_id>/pin/', pin_chat_message, name='chat_message_pin'),
    path('chat/<int:room_id>/message/<int:message_id>/react/', react_chat_message, name='chat_message_react'),
    path('chat/<int:room_id>/theme/', set_chat_theme, name='chat_theme'),
    path('api/chat/<int:room_id>/messages/', chat_messages_api, name='chat_messages_api'),
    path('api/chat/<int:room_id>/typing/', chat_typing_api, name='chat_typing_api'),
    path('api/live-status/', live_status_api, name='live_status_api'),
    path('api/notifications/counts/', notification_counts_api, name='notification_counts_api'),
    path('api/notifications/center/', notification_center_api, name='notification_center_api'),
    path('api/notifications/dismiss/', notification_dismiss_api, name='notification_dismiss_api'),
    path('api/notifications/dismiss-all/', notification_dismiss_all_api, name='notification_dismiss_all_api'),
    path('api/users/presence/', user_presence_api, name='user_presence_api'),

    path('weather/', weather, name='weather'),
    path('weather-icon/<str:icon_code>/<str:size>/', weather_icon_view, name='weather_icon'),
    path('obs-dashboard/', obs_dashboard, name='obs-dashboard'),
    path('spritkostenrechner/', spritkostenrechner, name='spritkostenrechner'),
    path('budget/', budget_tracker_view, name='budget_tracker'),
    path('budget/export/', budget_tracker_export_csv, name='budget_tracker_export'),

    path('human-benchmark/', human_benchmark, name='human-benchmark'),
    path('api/human-benchmark/scores/', human_benchmark_score_api, name='human-benchmark-score-api'),

    path('genius-search/', genius_search, name='genius-search'),
    path('avatar-wiki/', avatar_wiki, name='avatar-wiki'),
    path('api/avatar-characters/', avatar_characters_api, name='avatar-characters-api'),
    path('api/avatar-characters/<int:character_id>/', avatar_character_detail_api, name='avatar-character-detail-api'),
    path('api/genius/search/', genius_search_api, name='genius-search-api'),
    path('api/tankstellen/', tankstellen_api, name='tankstellen-api'),

    path('notes/', notes_view, name='notes'),
    path('notes/new/', note_create_view, name='note_create'),
    path('notes/<int:pk>/', note_detail_view, name='note_detail'),
    path('notes/<int:pk>/edit/', note_edit_view, name='note_edit'),
    path('notes/<int:pk>/delete/', note_delete_view, name='note_delete'),
    path('notes/<int:pk>/pin/', note_toggle_pin_view, name='note_toggle_pin'),
    path('notes/<int:pk>/archive/', note_toggle_archive_view, name='note_toggle_archive'),

    path('rechner/', calculator_view, name='calculator'),
    path('einheitenrechner/', unit_converter_view, name='unit_converter'),
    path('randomizer/', randomizer_tools_view, name='randomizer_tools'),
    path('qr-code/', qr_code_tool_view, name='qr_code_tool'),
    path('drift-circuit/', drift_circuit, name='drift-circuit'),
    path('snake-powerups/', snake_powerups, name='snake-powerups'),
    path('cookie-clicker/', cookie_clicker, name='cookie-clicker'),
    path('api/cookie-clicker/score/', cookie_clicker_score_api, name='cookie-clicker-score-api'),
    path('2048/', game_2048, name='game-2048'),
    path('api/2048/score/', game_2048_score_api, name='game-2048-score-api'),
    path('api/2048/activity/', game_2048_activity_api, name='game-2048-activity-api'),

    path('tic-tac-toe/', tictactoe_home, name='tictactoe_home'),
    path('tic-tac-toe/<slug:code>/', tictactoe_lobby, name='tictactoe_lobby'),
    path('tic-tac-toe/<slug:code>/invite/', tictactoe_invite_friend, name='tictactoe_invite_friend'),
    path('tic-tac-toe/invite/<int:invite_id>/', tictactoe_invite_response, name='tictactoe_invite_response'),
    path('tic-tac-toe/<slug:code>/leave/', tictactoe_leave, name='tictactoe_leave'),
    path('tic-tac-toe/<slug:code>/delete/', tictactoe_delete, name='tictactoe_delete'),
    path('api/tic-tac-toe/<slug:code>/state/', tictactoe_state_api, name='tictactoe_state_api'),
    path('api/tic-tac-toe/home-state/', tictactoe_home_state_api, name='tictactoe_home_state_api'),
    path('api/tic-tac-toe/<slug:code>/move/', tictactoe_move_api, name='tictactoe_move_api'),
    path('api/tic-tac-toe/<slug:code>/reset/', tictactoe_reset_api, name='tictactoe_reset_api'),

    path('vier-gewinnt/', connectfour_home, name='connectfour_home'),
    path('vier-gewinnt/<slug:code>/', connectfour_lobby, name='connectfour_lobby'),
    path('vier-gewinnt/<slug:code>/invite/', connectfour_invite_friend, name='connectfour_invite_friend'),
    path('vier-gewinnt/invite/<int:invite_id>/', connectfour_invite_response, name='connectfour_invite_response'),
    path('vier-gewinnt/<slug:code>/leave/', connectfour_leave, name='connectfour_leave'),
    path('vier-gewinnt/<slug:code>/delete/', connectfour_delete, name='connectfour_delete'),
    path('api/vier-gewinnt/home-state/', connectfour_home_state_api, name='connectfour_home_state_api'),
    path('api/vier-gewinnt/<slug:code>/state/', connectfour_state_api, name='connectfour_state_api'),
    path('api/vier-gewinnt/<slug:code>/move/', connectfour_move_api, name='connectfour_move_api'),
    path('api/vier-gewinnt/<slug:code>/reset/', connectfour_reset_api, name='connectfour_reset_api'),

    path('schiffe-versenken/', battleship_home, name='battleship_home'),
    path('schiffe-versenken/<slug:code>/', battleship_lobby, name='battleship_lobby'),
    path('schiffe-versenken/<slug:code>/invite/', battleship_invite_friend, name='battleship_invite_friend'),
    path('schiffe-versenken/invite/<int:invite_id>/', battleship_invite_response, name='battleship_invite_response'),
    path('schiffe-versenken/<slug:code>/leave/', battleship_leave, name='battleship_leave'),
    path('schiffe-versenken/<slug:code>/delete/', battleship_delete, name='battleship_delete'),
    path('api/schiffe-versenken/home-state/', battleship_home_state_api, name='battleship_home_state_api'),
    path('api/schiffe-versenken/<slug:code>/state/', battleship_state_api, name='battleship_state_api'),
    path('api/schiffe-versenken/<slug:code>/place/', battleship_place_api, name='battleship_place_api'),
    path('api/schiffe-versenken/<slug:code>/attack/', battleship_attack_api, name='battleship_attack_api'),
    path('api/schiffe-versenken/<slug:code>/reset/', battleship_reset_api, name='battleship_reset_api'),

    path('stadt-land-fluss/', stadtlandfluss_home, name='stadtlandfluss_home'),
    path('stadt-land-fluss/<slug:code>/', stadtlandfluss_lobby, name='stadtlandfluss_lobby'),
    path('stadt-land-fluss/<slug:code>/invite/', stadtlandfluss_invite_friend, name='stadtlandfluss_invite_friend'),
    path('stadt-land-fluss/invite/<int:invite_id>/', stadtlandfluss_invite_response, name='stadtlandfluss_invite_response'),
    path('stadt-land-fluss/<slug:code>/start/', stadtlandfluss_start, name='stadtlandfluss_start'),
    path('stadt-land-fluss/<slug:code>/continue/', stadtlandfluss_continue, name='stadtlandfluss_continue'),
    path('stadt-land-fluss/<slug:code>/restart/', stadtlandfluss_restart, name='stadtlandfluss_restart'),
    path('stadt-land-fluss/<slug:code>/leave/', stadtlandfluss_leave, name='stadtlandfluss_leave'),
    path('stadt-land-fluss/<slug:code>/delete/', stadtlandfluss_delete, name='stadtlandfluss_delete'),
    path('api/stadt-land-fluss/home-state/', stadtlandfluss_home_state_api, name='stadtlandfluss_home_state_api'),
    path('api/stadt-land-fluss/<slug:code>/state/', stadtlandfluss_state_api, name='stadtlandfluss_state_api'),
    path('api/stadt-land-fluss/<slug:code>/draft/', stadtlandfluss_draft_api, name='stadtlandfluss_draft_api'),
    path('api/stadt-land-fluss/<slug:code>/submit/', stadtlandfluss_submit_api, name='stadtlandfluss_submit_api'),
    path('api/stadt-land-fluss/<slug:code>/vote/', stadtlandfluss_vote_api, name='stadtlandfluss_vote_api'),


    path('hangman/', hangman_home, name='hangman_home'),
    path('hangman/<slug:code>/', hangman_lobby, name='hangman_lobby'),
    path('hangman/<slug:code>/invite/', hangman_invite_friend, name='hangman_invite_friend'),
    path('hangman/invite/<int:invite_id>/', hangman_invite_response, name='hangman_invite_response'),
    path('hangman/<slug:code>/leave/', hangman_leave, name='hangman_leave'),
    path('hangman/<slug:code>/delete/', hangman_delete, name='hangman_delete'),
    path('api/hangman/home-state/', hangman_home_state_api, name='hangman_home_state_api'),
    path('api/hangman/<slug:code>/state/', hangman_state_api, name='hangman_state_api'),
    path('api/hangman/<slug:code>/start/', hangman_start_api, name='hangman_start_api'),
    path('api/hangman/<slug:code>/word/', hangman_word_api, name='hangman_word_api'),
    path('api/hangman/<slug:code>/guess/', hangman_guess_api, name='hangman_guess_api'),
    path('api/hangman/<slug:code>/review/', hangman_review_api, name='hangman_review_api'),
    path('api/hangman/<slug:code>/reset/', hangman_reset_api, name='hangman_reset_api'),

    path('uno/', uno_home, name='uno_home'),
    path('uno/<slug:code>/', uno_lobby, name='uno_lobby'),
    path('uno/<slug:code>/invite/', uno_invite_friend, name='uno_invite_friend'),
    path('uno/invite/<int:invite_id>/', uno_invite_response, name='uno_invite_response'),
    path('uno/<slug:code>/leave/', uno_leave, name='uno_leave'),
    path('uno/<slug:code>/delete/', uno_delete, name='uno_delete'),
    path('api/uno/home-state/', uno_home_state_api, name='uno_home_state_api'),
    path('api/uno/<slug:code>/state/', uno_state_api, name='uno_state_api'),
    path('api/uno/<slug:code>/start/', uno_start_api, name='uno_start_api'),
    path('api/uno/<slug:code>/play/', uno_play_api, name='uno_play_api'),
    path('api/uno/<slug:code>/draw/', uno_draw_api, name='uno_draw_api'),
    path('api/uno/<slug:code>/pass/', uno_pass_api, name='uno_pass_api'),
    path('api/uno/<slug:code>/call/', uno_call_api, name='uno_call_api'),
    path('api/uno/<slug:code>/catch/', uno_catch_api, name='uno_catch_api'),
    path('api/uno/<slug:code>/reset/', uno_reset_api, name='uno_reset_api'),

    path('kniffel/', kniffel_home, name='kniffel_home'),
    path('kniffel/<slug:code>/', kniffel_lobby, name='kniffel_lobby'),
    path('kniffel/<slug:code>/invite/', kniffel_invite_friend, name='kniffel_invite_friend'),
    path('kniffel/invite/<int:invite_id>/', kniffel_invite_response, name='kniffel_invite_response'),
    path('kniffel/<slug:code>/leave/', kniffel_leave, name='kniffel_leave'),
    path('kniffel/<slug:code>/delete/', kniffel_delete, name='kniffel_delete'),
    path('api/kniffel/home-state/', kniffel_home_state_api, name='kniffel_home_state_api'),
    path('api/kniffel/<slug:code>/state/', kniffel_state_api, name='kniffel_state_api'),
    path('api/kniffel/<slug:code>/start/', kniffel_start_api, name='kniffel_start_api'),
    path('api/kniffel/<slug:code>/roll/', kniffel_roll_api, name='kniffel_roll_api'),
    path('api/kniffel/<slug:code>/score/', kniffel_score_api, name='kniffel_score_api'),
    path('api/kniffel/<slug:code>/reset/', kniffel_reset_api, name='kniffel_reset_api'),

    path('pong/', pong_home, name='pong_home'),
    path('pong/<slug:code>/', pong_lobby, name='pong_lobby'),
    path('pong/<slug:code>/invite/', pong_invite_friend, name='pong_invite_friend'),
    path('pong/invite/<int:invite_id>/', pong_invite_response, name='pong_invite_response'),
    path('pong/<slug:code>/leave/', pong_leave, name='pong_leave'),
    path('pong/<slug:code>/delete/', pong_delete, name='pong_delete'),
    path('api/pong/home-state/', pong_home_state_api, name='pong_home_state_api'),
    path('api/pong/<slug:code>/state/', pong_state_api, name='pong_state_api'),
    path('api/pong/<slug:code>/paddle/', pong_paddle_api, name='pong_paddle_api'),
    path('api/pong/<slug:code>/reset/', pong_reset_api, name='pong_reset_api'),

    path('skribble/', skribble_home, name='skribble_home'),
    path('skribble/<slug:code>/', skribble_lobby, name='skribble_lobby'),
    path('skribble/<slug:code>/invite/', skribble_invite_friend, name='skribble_invite_friend'),
    path('skribble/invite/<int:invite_id>/', skribble_invite_response, name='skribble_invite_response'),
    path('skribble/<slug:code>/avatar/', skribble_update_avatar, name='skribble_update_avatar'),
    path('skribble/<slug:code>/start/', skribble_start, name='skribble_start'),
    path('skribble/<slug:code>/restart/', skribble_restart, name='skribble_restart'),
    path('skribble/<slug:code>/continue/', skribble_continue_round, name='skribble_continue_round'),
    path('skribble/<slug:code>/leave/', skribble_leave_lobby, name='skribble_leave_lobby'),
    path('skribble/<slug:code>/delete/', skribble_delete_lobby, name='skribble_delete_lobby'),
    path('api/skribble/<slug:code>/state/', skribble_state_api, name='skribble_state_api'),
    path('api/skribble/<slug:code>/choose-word/', skribble_choose_word_api, name='skribble_choose_word_api'),
    path('api/skribble/<slug:code>/draw/', skribble_draw_api, name='skribble_draw_api'),
    path('api/skribble/<slug:code>/guess/', skribble_guess_api, name='skribble_guess_api'),

    path('stream-deck/', stream_deck, name='stream-deck'),
]
