from django.urls import path

from .views import (
    about,
    avatar_character_detail_api,
    avatar_characters_api,
    avatar_wiki,
    clock_view,
    drift_circuit,
    genius_search,
    genius_search_api,
    home,
    human_benchmark,
    human_benchmark_score_api,
    note_create_view,
    note_delete_view,
    note_edit_view,
    note_toggle_archive_view,
    note_toggle_pin_view,
    notes_view,
    obs_dashboard,
    signup,
    spritkostenrechner,
    stream_deck,
    tankstellen_api,
    unit_converter_view,
    weather,
)
from .profile_views import (
    block_user_view,
    delete_gallery_image_view,
    friends_list_view,
    friendship_action_view,
    profile_gallery_upload_view,
    profile_view,
    report_user_view,
    public_profile_view,
    users_view,
)
from .skribble_views import (
    skribble_choose_word_api,
    skribble_continue_round,
    skribble_delete_lobby,
    skribble_draw_api,
    skribble_guess_api,
    skribble_home,
    skribble_invite_friend,
    skribble_invite_response,
    skribble_leave_lobby,
    skribble_lobby,
    skribble_restart,
    skribble_start,
    skribble_state_api,
    skribble_update_avatar,
)
from .tictactoe_views import (
    tictactoe_home,
    tictactoe_delete,
    tictactoe_invite_friend,
    tictactoe_invite_response,
    tictactoe_leave,
    tictactoe_lobby,
    tictactoe_home_state_api,
    tictactoe_move_api,
    tictactoe_reset_api,
    tictactoe_state_api,
)
from .battleship_views import (
    battleship_attack_api,
    battleship_delete,
    battleship_home,
    battleship_home_state_api,
    battleship_invite_friend,
    battleship_invite_response,
    battleship_leave,
    battleship_lobby,
    battleship_place_api,
    battleship_reset_api,
    battleship_state_api,
)
from .chat_views import (
    chat_group_leave_view,
    chat_group_member_action_view,
    chat_group_settings_view,
    chat_messages_api,
    chat_view,
    create_group_chat,
    delete_chat_message,
    react_chat_message,
    send_chat_message,
    start_direct_chat,
)
from .notification_views import notification_center_api, notification_counts_api
from .platform_views import (
    favorite_toggle_view,
    favorites_view,
    feedback_view,
    inbox_mark_read_view,
    inbox_view,
)

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('', home, name='home'),
    path('home/', home, name='home'),
    path('about/', about, name='about'),
    path('favorites/', favorites_view, name='favorites'),
    path('favorites/<slug:tool_key>/toggle/', favorite_toggle_view, name='favorite_toggle'),
    path('inbox/', inbox_view, name='inbox'),
    path('inbox/read/', inbox_mark_read_view, name='inbox_mark_read'),
    path('feedback/', feedback_view, name='feedback'),
    path('uhr/', clock_view, name='clock'),

    path('profile/', profile_view, name='profile'),
    path('profile/gallery/upload/', profile_gallery_upload_view, name='profile_gallery_upload'),
    path('profile/gallery/<int:image_id>/delete/', delete_gallery_image_view, name='profile_gallery_delete'),
    path('users/', users_view, name='users'),
    path('users/<int:user_id>/', public_profile_view, name='public_profile'),
    path('users/<int:user_id>/friends/', friends_list_view, name='friends_list'),
    path('users/<int:user_id>/friendship/', friendship_action_view, name='friendship_action'),
    path('users/<int:user_id>/block/', block_user_view, name='block_user'),
    path('users/<int:user_id>/report/', report_user_view, name='report_user'),

    path('chat/', chat_view, name='chat'),
    path('chat/<int:room_id>/', chat_view, name='chat_room'),
    path('chat/direct/<int:user_id>/', start_direct_chat, name='chat_direct'),
    path('chat/group/new/', create_group_chat, name='chat_group_create'),
    path('chat/<int:room_id>/group/settings/', chat_group_settings_view, name='chat_group_settings'),
    path('chat/<int:room_id>/group/leave/', chat_group_leave_view, name='chat_group_leave'),
    path('chat/<int:room_id>/group/member/<int:user_id>/', chat_group_member_action_view, name='chat_group_member_action'),
    path('chat/<int:room_id>/send/', send_chat_message, name='chat_send'),
    path('chat/<int:room_id>/message/<int:message_id>/delete/', delete_chat_message, name='chat_message_delete'),
    path('chat/<int:room_id>/message/<int:message_id>/react/', react_chat_message, name='chat_message_react'),
    path('api/chat/<int:room_id>/messages/', chat_messages_api, name='chat_messages_api'),
    path('api/notifications/counts/', notification_counts_api, name='notification_counts_api'),
    path('api/notifications/center/', notification_center_api, name='notification_center_api'),

    path('weather/', weather, name='weather'),
    path('obs-dashboard/', obs_dashboard, name='obs-dashboard'),
    path('spritkostenrechner/', spritkostenrechner, name='spritkostenrechner'),

    path('human-benchmark/', human_benchmark, name='human-benchmark'),
    path('api/human-benchmark/scores/', human_benchmark_score_api, name='human-benchmark-score-api'),

    path('genius-search/', genius_search, name='genius-search'),
    path('avatar-wiki/', avatar_wiki, name='avatar-wiki'),
    path('api/avatar-characters/', avatar_characters_api, name='avatar-characters-api'),
    path('api/avatar-characters/<int:character_id>/', avatar_character_detail_api, name='avatar-character-detail-api'),
    path('api/genius/search/', genius_search_api, name='genius-search-api'),
    path('api/tankstellen/', tankstellen_api, name='tankstellen-api'),

    path('notes/', notes_view, name='notes'),
    path('notes/new/', note_create_view, name='note_create'),
    path('notes/<int:pk>/edit/', note_edit_view, name='note_edit'),
    path('notes/<int:pk>/delete/', note_delete_view, name='note_delete'),
    path('notes/<int:pk>/pin/', note_toggle_pin_view, name='note_toggle_pin'),
    path('notes/<int:pk>/archive/', note_toggle_archive_view, name='note_toggle_archive'),

    path('einheitenrechner/', unit_converter_view, name='unit_converter'),
    path('drift-circuit/', drift_circuit, name='drift-circuit'),

    path('tic-tac-toe/', tictactoe_home, name='tictactoe_home'),
    path('tic-tac-toe/<slug:code>/', tictactoe_lobby, name='tictactoe_lobby'),
    path('tic-tac-toe/<slug:code>/invite/', tictactoe_invite_friend, name='tictactoe_invite_friend'),
    path('tic-tac-toe/invite/<int:invite_id>/', tictactoe_invite_response, name='tictactoe_invite_response'),
    path('tic-tac-toe/<slug:code>/leave/', tictactoe_leave, name='tictactoe_leave'),
    path('tic-tac-toe/<slug:code>/delete/', tictactoe_delete, name='tictactoe_delete'),
    path('api/tic-tac-toe/<slug:code>/state/', tictactoe_state_api, name='tictactoe_state_api'),
    path('api/tic-tac-toe/home-state/', tictactoe_home_state_api, name='tictactoe_home_state_api'),
    path('api/tic-tac-toe/<slug:code>/move/', tictactoe_move_api, name='tictactoe_move_api'),
    path('api/tic-tac-toe/<slug:code>/reset/', tictactoe_reset_api, name='tictactoe_reset_api'),

    path('schiffe-versenken/', battleship_home, name='battleship_home'),
    path('schiffe-versenken/<slug:code>/', battleship_lobby, name='battleship_lobby'),
    path('schiffe-versenken/<slug:code>/invite/', battleship_invite_friend, name='battleship_invite_friend'),
    path('schiffe-versenken/invite/<int:invite_id>/', battleship_invite_response, name='battleship_invite_response'),
    path('schiffe-versenken/<slug:code>/leave/', battleship_leave, name='battleship_leave'),
    path('schiffe-versenken/<slug:code>/delete/', battleship_delete, name='battleship_delete'),
    path('api/schiffe-versenken/home-state/', battleship_home_state_api, name='battleship_home_state_api'),
    path('api/schiffe-versenken/<slug:code>/state/', battleship_state_api, name='battleship_state_api'),
    path('api/schiffe-versenken/<slug:code>/place/', battleship_place_api, name='battleship_place_api'),
    path('api/schiffe-versenken/<slug:code>/attack/', battleship_attack_api, name='battleship_attack_api'),
    path('api/schiffe-versenken/<slug:code>/reset/', battleship_reset_api, name='battleship_reset_api'),

    path('skribble/', skribble_home, name='skribble_home'),
    path('skribble/<slug:code>/', skribble_lobby, name='skribble_lobby'),
    path('skribble/<slug:code>/invite/', skribble_invite_friend, name='skribble_invite_friend'),
    path('skribble/invite/<int:invite_id>/', skribble_invite_response, name='skribble_invite_response'),
    path('skribble/<slug:code>/avatar/', skribble_update_avatar, name='skribble_update_avatar'),
    path('skribble/<slug:code>/start/', skribble_start, name='skribble_start'),
    path('skribble/<slug:code>/restart/', skribble_restart, name='skribble_restart'),
    path('skribble/<slug:code>/continue/', skribble_continue_round, name='skribble_continue_round'),
    path('skribble/<slug:code>/leave/', skribble_leave_lobby, name='skribble_leave_lobby'),
    path('skribble/<slug:code>/delete/', skribble_delete_lobby, name='skribble_delete_lobby'),
    path('api/skribble/<slug:code>/state/', skribble_state_api, name='skribble_state_api'),
    path('api/skribble/<slug:code>/choose-word/', skribble_choose_word_api, name='skribble_choose_word_api'),
    path('api/skribble/<slug:code>/draw/', skribble_draw_api, name='skribble_draw_api'),
    path('api/skribble/<slug:code>/guess/', skribble_guess_api, name='skribble_guess_api'),

    path('stream-deck/', stream_deck, name='stream-deck'),
]
